Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2022-09, with the labels that each got.

#178 chore: Update LICENSE
  LICENSE
Labels: chore

#179 fix: flexible blocks' last item is always white
  src/lib-components/FlexibleBlocks.vue
  src/stories/FlexibleBlocks.stories.js
Labels: bugfix

#180 fix: APPS-1877 update block staff article item
  src/lib-components/BlockStaffArticleList.vue
Labels: bugfix

#173 refactor: logic to open external links in new tab
  dev/serve.vue
  src/lib-components/BannerText.vue
  src/lib-components/BlockCardWithIllustration.vue
  src/lib-components/BlockHighlight.vue
  src/lib-components/BlockHours.vue
  src/lib-components/BlockSimpleCard.vue
  src/lib-components/BlockSpaces.vue
  src/lib-components/BlockSponsor.vue
  src/lib-components/ButtonLink.vue
  src/lib-components/FooterPrimary.vue
  src/lib-components/FooterSock.vue
  src/lib-components/GridGallery.vue
  src/lib-components/HeaderMainResponsive.vue
  src/lib-components/NavMenuItem.vue
  src/lib-components/NavMenuItemResponsive.vue
  src/lib-components/NavPrimary.vue
  src/lib-components/NavSecondary.vue
  src/lib-components/SmartLink.vue
  src/mixins/formatLinkTarget.js
  src/mixins/isInternalLink.js
  src/stories/BannerHeader.spec.js
  src/stories/BannerHeader.stories.js
  src/stories/BannerText.spec.js
  src/stories/BannerText.stories.js
  src/stories/BlockCardWithIllustration.spec.js
  src/stories/BlockSimpleCard.spec.js
  src/stories/ButtonLink.spec.js
  src/stories/FooterSock.spec.js
  src/stories/FooterSock.stories.js
  src/stories/MediaGallery_NewLightbox.spec.js
  src/stories/NavPrimary.spec.js
  src/stories/NavSecondary.spec.js
  src/stories/NavSecondary.stories.js
  src/stories/SmartLink.spec.js
  src/stories/SmartLink.stories.js
  src/stories/mock/Flexible_RichText.js
  tsconfig.json
Labels: bugfix

#182 fix: APPS-1890 ucla library logo bug fixed
  src/lib-components/FooterMain.vue
  src/lib-components/FooterPrimary.vue
  src/lib-components/NavSecondary.vue
  src/stories/FooterPrimary.stories.js
Labels: bugfix

#183 fix: add default image to BlockStaffArticleList
  src/lib-components/BlockStaffArticleList.vue
  src/stories/BlockStaffArticleList.stories.js
Labels: bugfix

#184 fix: Apps 1849 update simple cards
  src/lib-components/BlockStaffArticleList.vue
  src/lib-components/Flexible/SimpleCards.vue
  src/stories/Flexible_SimpleCards.stories.js
  src/stories/mock/Flexible_SimpleCards.js
Labels: bugfix

#185 fix: use the desktop Header in static build
  src/lib-components/HeaderSmart.vue
Labels: bugfix

#186 fix: update navbreadcrumb
  src/mixins/getMeapParentPageTitle.js
  src/mixins/getParentPageUrl.js
Labels: bugfix

#187 fix: disappearing menus, part 2
  src/lib-components/HeaderMainResponsive.vue
  src/lib-components/HeaderSmart.vue
Labels: bugfix

#188 feat: updates section-banner spacing
  src/lib-components/SectionWrapper.vue
Labels: Ready for Review ​🎯​, feature

#189 fix: add blog to breadcrumb
  src/mixins/getParentPageTitle.js
Labels: bugfix

#190 fix: APPS-1912 Update Byline in BannerHeader
  src/lib-components/BannerHeader.vue
  src/stories/BannerHeader.stories.js
Labels: fix

#193 fix: removes svg and updates featured layout
  src/lib-components/GridGallery.vue
Labels: fix

#192 fix: clear focus when closing Nav menu
  src/lib-components/NavPrimary.vue
Labels: bugfix, Ready for Review ​🎯​, fix

#196 fix: move text
  src/lib-components/BannerHeader.vue
Labels: fix

#199 feat: Update prompt mixin and Create Flexible_GridGalleryCards component
  dev/serve.vue
  src/lib-components/Flexible/CardWithImage.vue
  src/lib-components/Flexible/GridGalleryCards.vue
  src/lib-components/Flexible/Highlight.vue
  src/lib-components/FlexibleBlocks.vue
  src/lib-components/FooterSponsor.vue
  src/lib-components/GridGallery.vue
  src/lib-components/NavPrimary.vue
  src/lib-components/index.js
  src/mixins/getPrompt.js
  src/stories/Flexible_BannerFeatured.stories.js
  src/stories/Flexible_GridGalleryCards.spec.js
  src/stories/Flexible_GridGalleryCards.stories.js
Labels: feature

#197 feat: Add FlexibleImpactNumberCards
  src/lib-components/Flexible/ImpactNumberCards.vue
  src/lib-components/FlexibleBlocks.vue
  src/lib-components/ImpactNumberCard.vue
  src/lib-components/index.js
  src/stories/Flexible_ImpactNumberCards.spec.js
  src/stories/Flexible_ImpactNumberCards.stories.js
  src/stories/ImpactNumberCard.spec.js
  src/stories/ImpactNumberCard.stories.js
  src/stories/PullQuote.spec.js
Labels: feature

#194 ci: auto-commit eslint fixes
  .github/workflows/ci.yml
Labels: ci

#200 fix: update spacing and text-size on gridgallerycards
  src/lib-components/Flexible/GridGalleryCards.vue
  src/lib-components/GridGallery.vue
Labels: bugfix

#198 fix: APPS-1713 Add sectionTitle & sectionSummary to FPB collections
  dev/serve.vue
  src/lib-components/Flexible/AssociatedTopicCards.vue
  src/lib-components/Flexible/CardWithImage.vue
  src/lib-components/Flexible/Form.vue
  src/lib-components/Flexible/Highlight.vue
  src/lib-components/Flexible/ImpactNumbersCarousel.vue
  src/lib-components/Flexible/MediaGallery.vue
  src/lib-components/Flexible/MediaWithText.vue
  src/lib-components/ImpactNumbersCarousel.vue
  src/lib-components/SectionCardsWithIllustrations.vue
  src/stories/Flexible_BannerFeatured.stories.js
  src/stories/Flexible_Form.stories.js
  src/stories/Flexible_GridGalleryCards.stories.js
  src/stories/Flexible_ImpactNumberCards.stories.js
  src/stories/Flexible_ImpactNumbersCarousel.stories.js
  src/stories/SectionCardsWithIllustrations.stories.js
  src/stories/mock/BlockMediaWithText.js
  src/stories/mock/Flexible_AssociatedTopicCards.js
  src/stories/mock/Flexible_CardWithImage.js
  src/stories/mock/Flexible_Highlight.js
  src/stories/mock/Flexible_MediaGallery.js
  src/stories/mock/Flexible_MediaWithText.js
  src/stories/mock/Flexible_RichText.js
  src/stories/mock/Flexible_SimpleCards.js
Labels: fix

#195 fix: fixed impactNumbersCarousel image
  src/lib-components/Flexible/MediaGallery/NewLightbox.vue
  src/lib-components/ImpactNumbersCarousel.vue
  src/stories/Flexible_ImpactNumbersCarousel.stories.js
  src/stories/ImpactNumbersCarousel.stories.js
  src/styles/vue-glide.scss
Labels: bugfix

#202 fix: refactor NavBreadcrumb
  dev/serve.vue
  src/lib-components/NavBreadcrumb.vue
  src/mixins/getMeapParentPageTitle.js
  src/mixins/getParentPageTitle.js
  src/mixins/getParentPageUrl.js
  src/stories/NavBreadcrumb.stories.js
Labels: refactor
