Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2022-07, with the labels that each got.

#38 fix: update form css
  src/lib-components/Flexible/Form.vue
Labels: bugfix

#40 feat: add simple cards
  dev/serve.vue
  src/lib-components/SimpleCards.vue
  src/lib-components/index.js
  src/stories/SimpleCards.spec.js
  src/stories/SimpleCards.stories.js
Labels: feature

#43 feat: Flexible Media With Text, Simple Cards, Call ToAction Two Up
  dev/serve.vue
  src/lib-components/Flexible/CtaBlock2Up.vue
  src/lib-components/Flexible/MediaWithText.vue
  src/lib-components/Flexible/SimpleCards.vue
  src/lib-components/FlexibleBlocks.vue
  src/lib-components/index.js
  src/stories/Flexible_CallToAction2Up.spec.js
  src/stories/Flexible_CallToAction2Up.stories.js
  src/stories/Flexible_MediaWithText.spec.js
  src/stories/Flexible_MediaWithText.stories.js
  src/stories/Flexible_SimpleCards.spec.js
  src/stories/Flexible_SimpleCards.stories.js
Labels: feature

#46 feat: APPS-686 add section staff component
  dev/serve.vue
  src/lib-components/SectionStaffList.vue
  src/lib-components/index.js
  src/stories/BlockSpaces.stories.js
  src/stories/SectionDualMasonry.stories.js
  src/stories/SectionSpacesList.stories.js
  src/stories/SectionStaffList.spec.js
  src/stories/SectionStaffList.stories.js
Labels: feature

#53 feat: Add media gallery
  dev/serve.vue
  package-lock.json
  package.json
  src/lib-components/Flexible/MediaGallery.vue
  src/lib-components/Flexible/MediaGallery/BannerImage.vue
  src/lib-components/Flexible/MediaGallery/Lightbox.vue
  src/lib-components/Flexible/MediaGallery/NewLightbox.vue
  src/lib-components/Flexible/MediaGallery/ThumbnailCard.vue
  src/lib-components/FlexibleBlocks.vue
  src/lib-components/MediaBadge.vue
  src/lib-components/index.js
  src/stories/Flexible_MediaGallery.spec.js
  src/stories/Flexible_MediaGallery.stories.js
Labels: Ready for Review ​🎯​

#58 feat: add impact report components
  dev/serve.vue
  src/lib-components/GridGallery.vue
  src/lib-components/ImpactRichText.vue
  src/lib-components/StoryWithImage.vue
  src/lib-components/index.js
  src/stories/GridGallery.spec.js
  src/stories/GridGallery.stories.js
  src/stories/ImpactRichText.spec.js
  src/stories/ImpactRichText.stories.js
  src/stories/StoryWithImage.spec.js
  src/stories/StoryWithImage.stories.js
  src/stories/impact-report_index.json
Labels: Ready for Review ​🎯​

#59 fix: add media gallery stories
  src/lib-components/Flexible/MediaGallery/Lightbox.vue
  src/stories/MediaBadge.spec.js
  src/stories/MediaBadge.stories.js
  src/stories/MediaGallery_BannerImage.spec.js
  src/stories/MediaGallery_BannerImage.stories.js
  src/stories/MediaGallery_NewLightbox.spec.js
  src/stories/MediaGallery_NewLightbox.stories.js
  src/stories/MediaGallery_ThumbnailCard.spec.js
  src/stories/MediaGallery_ThumbnailCard.stories.js
Labels: Ready for Review ​🎯​

#52 feat: Apps-1650 - move global components to vuejs component package
  dev/serve.js
  dev/serve.vue
  src/lib-components/HeaderMain.vue
  src/lib-components/HeaderMainResponsive.vue
  src/lib-components/HeaderSmart.vue
  src/lib-components/NavMenuItemResponsive.vue
  src/lib-components/index.js
  src/stories/HeaderMainResponsive.spec.js
  src/stories/HeaderMainResponsive.stories.js
  src/stories/HeaderSmart.spec.js
  src/stories/HeaderSmart.stories.js
Labels: Ready for Review ​🎯​

#65 feat: add impact number carousel
  dev/serve.vue
  src/lib-components/ImpactNumbersCarousel.vue
  src/lib-components/index.js
  src/stories/ImpactNumbersCarousel.spec.js
  src/stories/ImpactNumbersCarousel.stories.js
Labels: Ready for Review ​🎯​

#61 feat: APPS-1695 add search generic
  dev/serve.vue
  src/lib-components/BaseCheckboxGroup.vue
  src/lib-components/BaseRadioGroup.vue
  src/lib-components/SearchGeneric.vue
  src/lib-components/SearchGenericFilterButtons.vue
  src/lib-components/SearchGenericViewModes.vue
  src/lib-components/index.js
  src/stories/GridGallery.spec.js
  src/stories/MediaBadge.spec.js
  src/stories/MediaGallery_BannerImage.spec.js
  src/stories/MediaGallery_NewLightbox.spec.js
  src/stories/MediaGallery_ThumbnailCard.spec.js
  src/stories/SearchGeneric.stories.js
  src/stories/SectionTeaserHighlight.stories.js
  src/stories/StoryWithImage.spec.js
Labels: Work in progress / Draft ✍

#70 feat: APPS-1684 section pagination, staff article list, & orcid pub
  dev/serve.vue
  src/lib-components/SectionPagination.vue
  src/lib-components/SectionStaffArticleList.vue
  src/lib-components/SectionStaffOrcidPublications.vue
  src/lib-components/index.js
  src/stories/ImpactNumbersCarousel.spec.js
  src/stories/SectionPagination.spec.js
  src/stories/SectionPagination.stories.js
  src/stories/SectionStaffArticleList.spec.js
  src/stories/SectionStaffArticleList.stories.js
  src/stories/SectionStaffOrcidPublications.stories.js
Labels: feature

#75 feat: add MEAP footer sponsor
  dev/serve.vue
  package-lock.json
  package.json
  src/lib-components/FooterSponsor.vue
  src/lib-components/index.js
  src/stories/FooterSponsor.spec.js
  src/stories/FooterSponsor.stories.js
  src/stories/ImpactNumbersCarousel.spec.js
Labels: Ready for Review ​🎯​

#77 fix: css changes to components
  src/lib-components/FlexibleBlocks.vue
  src/lib-components/MastheadSecondary.vue
  src/mixins/getParentPageTitle.js
Labels: Ready for Review ​🎯​

#76 feat: Add MEAP theme to MastheadSecondary
  src/lib-components/MastheadSecondary.vue
  src/stories/MastheadSecondary.spec.js
  src/stories/MastheadSecondary.stories.js
Labels: Ready for Review ​🎯​, feature

#81 fix: update getparentpage logic
  src/mixins/getParentPageTitle.js
Labels: Ready for Review ​🎯​

#87 feat: add readMe with tips and insights
  README.md
Labels: documentation

#88 fix: Footer sponsor change
  src/lib-components/FooterSponsor.vue
Labels: Ready for Review ​🎯​

#92 fix: Fix for squashed button text in BannerFeatured
  src/lib-components/BannerFeatured.vue
Labels: bugfix, Ready for Review ​🎯​

#83 feat: APPS-1707 Update components in vue component library npm repo
  dev/serve.vue
  src/lib-components/BannerHeader.vue
  src/lib-components/BannerText.vue
  src/lib-components/BlockAmenities.vue
  src/lib-components/BlockCallToAction.vue
  src/lib-components/BlockCampusMap.vue
  src/lib-components/BlockLocationListItem.vue
  src/lib-components/FlexibleBlocks.vue
  src/lib-components/index.js
  src/stories/BannerText.stories.js
  src/stories/BlockAmenities.spec.js
  src/stories/BlockAmenities.stories.js
Labels: Ready for Review ​🎯​

#91 fix: APPS-1621 project page components fixes
  src/lib-components/BannerHeader.vue
  src/lib-components/BannerText.vue
  src/mixins/getParentPageTitle.js
  src/stories/BannerText.stories.js
Labels: Ready for Review ​🎯​

#82 feat: APPS-1635 create nav secondary for microsites
  dev/serve.vue
  src/lib-components/ButtonLink.vue
  src/lib-components/HeaderSticky.vue
  src/lib-components/NavSecondary.vue
  src/stories/ButtonLink.stories.js
  src/stories/NavSecondary.stories.js
  src/stories/mock-api.json
Labels: Ready for Review ​🎯​
