Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2022-10, with the labels that each got.

#203 fix: updates BlockStaffDetail spacing
  src/lib-components/BlockStaffDetail.vue
Labels: fix

#205 fix: impact report video, card with image and highlight
  dev/serve.vue
  src/lib-components/Flexible/BannerFeatured.vue
  src/lib-components/Flexible/CardWithImage.vue
  src/lib-components/Flexible/Highlight.vue
  src/stories/Flexible_BannerFeatured.stories.js
  src/stories/mock/Flexible_CardWithImage.js
  src/stories/mock/Flexible_Highlight.js
Labels: feature

#206 feat: Apps 1907 block form style
  src/lib-components/BlockForm.vue
  src/mixins/isInternalLink.js
  src/stories/BlockForm.stories.js
Labels: feature

#207 fix: byline on banner text
  src/lib-components/BannerText.vue
  src/stories/BannerText.stories.js
Labels: fix

#209 fix: Revert byline on banner text
  src/lib-components/BannerText.vue
  src/stories/BannerText.stories.js
Labels: fix

#201 feat: compute smart header levels
  src/lib-components/FlexibleBlocks.vue
  src/lib-components/SectionHeader.vue
  src/lib-components/SectionWrapper.vue
  src/stories/SectionHeader.spec.js
  src/stories/SectionHeader.stories.js
  src/stories/SectionWrapper.spec.js
  src/stories/SectionWrapper.stories.js
  tsconfig.json
Labels: enhancement, feature

#208 feat: Apps 1710 libcal events block form
  .env
  .env.example
  src/lib-components/BannerFeatured.vue
  src/lib-components/BannerHeader.vue
  src/lib-components/BannerText.vue
  src/lib-components/BlockForm.vue
  src/stories/BannerFeatured.stories.js
  src/stories/BannerHeader.stories.js
  src/stories/BannerText.stories.js
  src/stories/BlockForm.spec.js
  src/stories/BlockForm.stories.js
  src/stories/Flexible_BannerFeatured.stories.js
  src/stories/mock/BlockFormData.json
Labels: feature, Work in progress / Draft ✍

#212 feat: MediaItem component
  src/lib-components/Media/Item.vue
  src/stories/MediaItem.spec.js
  src/stories/MediaItem.stories.js
Labels: feature

#213 feat: Apps 1895 anchor link nuxt id update
  src/lib-components/SectionSpacesList.vue
Labels: feature

#217 chore: sectionWrapper for the banner-header
  src/lib-components/SectionWrapper.vue
Labels: chore

#216 feat: Apps 1985 update block form
  src/lib-components/BlockForm.vue
  src/stories/BlockForm.stories.js
Labels: feature

#215 fix: Apps 1989 update molecule
  src/lib-components/BannerText.vue
Labels: fix

#219 feat: updates NavPrimary and BannerText spacing
  src/lib-components/BannerText.vue
  src/lib-components/NavPrimary.vue
Labels: feature

#220 fix: APPS-1996 banner featured image video logic
  src/lib-components/BannerFeatured.vue
  src/lib-components/Flexible/BannerFeatured.vue
  src/stories/BannerFeatured.stories.js
  src/stories/BannerHeader.stories.js
  src/stories/MediaItem.stories.js
  src/stories/ResponsiveVideo.stories.js
  src/stories/mock-api.json
Labels: bugfix

#221 fix: banner header image video logic
  src/lib-components/BannerFeatured.vue
  src/lib-components/BannerHeader.vue
  src/stories/BannerHeader.stories.js
Labels: bugfix

#222 fix: APPS-877 update search-generic component to sync filters
  dev/serve.vue
  src/lib-components/BaseCheckboxGroup.vue
  src/lib-components/BaseRadioGroup.vue
  src/lib-components/SearchGeneric.vue
  src/lib-components/SearchGenericFilterButtons.vue
  src/stories/SearchGeneric.stories.js
Labels: fix

#223 fix: add check for email required later in the lifecycle
  src/lib-components/BlockForm.vue
Labels: bugfix
