Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2022-12, with the labels that each got.

#264 fix: APPS-2080 Link title on the bannerFeatured component
  src/lib-components/BannerFeatured.vue
Labels: fix

#265 feat: updates media gallery, impact carousel, and card spacing for collections
  src/lib-components/Flexible/MediaGallery.vue
  src/lib-components/ImpactNumbersCarousel.vue
  src/lib-components/SectionTeaserCard.vue
  src/lib-components/SectionTeaserHighlight.vue
Labels: feature

#266 refactor: refactor masthead primary search links
  src/lib-components/MastheadPrimary.vue
  src/stories/MastheadPrimary.stories.js
Labels: refactor

#259 feat: APPS-2043 add checkbox component
  src/lib-components/BlockDropdownCheckbox.vue
  src/stories/BlockDropdownCheckbox.spec.js
  src/stories/BlockDropdownCheckbox.stories.js
Labels: feature

#268 fix: update masthead primary story and add smart-link to search home
  src/lib-components/SearchHome.vue
  src/stories/MastheadPrimary.stories.js
Labels: bugfix

#267 fix: bannerFeatured - choose to link to title
  src/lib-components/BannerFeatured.vue
  src/stories/BannerFeatured.stories.js
Labels: fix

#270 fix: apply consistent padding to tablet sized navbreadcrumb
  src/lib-components/NavBreadcrumb.vue
Labels: fix

#272 feat: ShowHide component
  src/lib-components/BlockShowHide.vue
  src/lib-components/ButtonHide.vue
  src/lib-components/ButtonShow.vue
  src/lib-components/SectionSpacesList.vue
  src/lib-components/SectionTeaserList.vue
  src/stories/BlockShowHide.spec.js
  src/stories/BlockShowHide.stories.js
  src/stories/ButtonHide.spec.js
  src/stories/ButtonHide.stories.js
  src/stories/ButtonShow.spec.js
  src/stories/ButtonShow.stories.js
  src/stories/SectionSpacesList.spec.js
  src/stories/SectionSpacesList.stories.js
  src/stories/SectionTeaserList.spec.js
  src/stories/SectionTeaserList.stories.js
Labels: feature

#274 feat: APPS-1881 use rich-text in masthead component
  src/lib-components/MastheadSecondary.vue
  src/stories/MastheadSecondary.stories.js
Labels: feature

#273 feat: location listing component qa
  src/lib-components/BlockLocationListItem.vue
  src/lib-components/BlockStaffList.vue
  src/lib-components/SectionLocationList.vue
  src/stories/Flexible_Form.spec.js
Labels: feature

#275 feat: APPS-2044 Add SinglCheckbox component for staff subject areas on search generic component
  src/lib-components/BlockDropdownCheckbox.vue
  src/lib-components/SearchGeneric.vue
  src/lib-components/SearchGenericFilterButtons.vue
  src/lib-components/SingleCheckbox.vue
  src/lib-components/index.js
  src/stories/BlockDropdownCheckbox.spec.js
  src/stories/SearchGeneric.stories.js
  src/stories/SingleCheckbox.spec.js
  src/stories/SingleCheckbox.stories.js
Labels: feature

#269 feat: added smart-link to button-more
  src/lib-components/ButtonMore.vue
  src/lib-components/SmartLink.vue
  src/stories/ButtonMore.stories.js
Labels: feature

#276 fix: update masthead text color to white
  src/lib-components/MastheadSecondary.vue
Labels: fix

#279 feat: APPS-2087 include lang attribute in block staff list detail
  src/lib-components/BlockStaffDetail.vue
  src/lib-components/BlockStaffList.vue
  src/lib-components/SectionStaffList.vue
  src/stories/BlockStaffDetail.stories.js
  src/stories/BlockStaffList.stories.js
  src/stories/SectionStaffList.stories.js
Labels: feature

#278 feat: location detail component QA
  src/lib-components/BlockHighlight.vue
  src/lib-components/SectionTeaserList.vue
Labels: feature

#277 refactor: improvements and fixes to ButtonLink and SiteNotificationAlert
  src/lib-components/ButtonLink.vue
  src/lib-components/SiteNotificationAlert.vue
  src/lib-components/SmartLink.vue
  src/stories/ButtonLink.stories.js
Labels: refactor

#282 feat: APPS-2106 Add Remove filters to search-generic
  dev/serve.vue
  package-lock.json
  package.json
  src/lib-components/BlockRemoveSearchFilter.vue
  src/lib-components/SearchGeneric.vue
  src/lib-components/SectionRemoveSearchFilter.vue
  src/lib-components/SectionSearchFilter.vue
  src/lib-components/index.js
  src/stories/BlockCallToAction.stories.js
  src/stories/BlockRemoveSearchFilter.spec.js
  src/stories/BlockRemoveSearchFilter.stories.js
  src/stories/BlockSearchFilter.spec.js
  src/stories/BlockSearchFilter.stories.js
  src/stories/SearchGeneric.stories.js
  src/stories/SectionRemoveSearchFilter.spec.js
  src/stories/SectionRemoveSearchFilter.stories.js
  src/stories/SectionSearchFilter.spec.js
  src/stories/SectionSearchFilter.stories.js
Labels: feature

#283 feat: search components QA
  src/lib-components/SearchGeneric.vue
  src/lib-components/SearchHome.vue
  src/lib-components/SingleCheckbox.vue
Labels: feature

#280 fix: events qa
  src/lib-components/BannerFeatured.vue
  src/lib-components/BlockCallToAction.vue
  src/lib-components/BlockForm.vue
  src/lib-components/BlockHighlight.vue
  src/lib-components/ButtonHide.vue
  src/lib-components/ButtonShow.vue
  src/lib-components/SectionTeaserList.vue
Labels: fix

#284 feat: updates homepage component spacing and opacity
  src/lib-components/MastheadPrimary.vue
  src/lib-components/SearchHome.vue
  src/lib-components/SectionDualMasonry.vue
Labels: feature

#285 fix: sectionDualMasonary date format and button text
  src/lib-components/BlockEvent.vue
  src/lib-components/SectionDualMasonry.vue
  src/mixins/formatEventDates.js
  src/stories/SectionDualMasonry.stories.js
  src/stories/mock-api.json
Labels: bugfix

#287 fix: strip meap/ from uri to allow duplicate general content pages like about in meap and library website
  src/lib-components/BannerFeatured.vue
  src/lib-components/BannerHeader.vue
  src/lib-components/Flexible/AssociatedTopicCards.vue
  src/lib-components/Flexible/BannerFeatured.vue
  src/lib-components/Flexible/CardWithImage.vue
  src/lib-components/Flexible/GridGalleryCards.vue
  src/lib-components/Flexible/Highlight.vue
  src/lib-components/Flexible/SimpleCards.vue
  src/mixins/stripMeapFromURI.js
Labels: feature

#286 feat: add alternativeName to generic list and highlight components
  .github/workflows/ci.yml
  .github/workflows/percy.yml
  .github/workflows/publish-to-npm.yml
  .github/workflows/setup-workspace/action.yml
  src/lib-components/BannerText.vue
  src/lib-components/BlockGenericList.vue
  src/lib-components/BlockHighlight.vue
  src/stories/BannerText.stories.js
  src/stories/BlockGenericList.stories.js
  src/stories/BlockHighlight.stories.js
Labels: feature

#288 fix: add alternativeName and language to sections
  src/lib-components/SectionGenericList.vue
  src/lib-components/SectionTeaserHighlight.vue
Labels: fix
