Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2022-08, with the labels that each got.

#90 feat: add title prop to headerSmart
  dev/serve.vue
  src/lib-components/HeaderMain.vue
  src/lib-components/HeaderSmart.vue
  src/store/index.js
  src/store/modules/headerSmart.js
  src/stories/HeaderSmart.stories.js
Labels: Ready for Review ​🎯​

#100 fix: APPS-1758 lazy load components
  build/rollup.config.js
  src/lib-components/BannerFeatured.vue
  src/lib-components/BannerHeader.vue
  src/lib-components/BannerText.vue
  src/lib-components/BlockAmenities.vue
  src/lib-components/BlockCallToAction.vue
  src/lib-components/BlockCardWithIllustration.vue
  src/lib-components/BlockHighlight.vue
  src/lib-components/BlockLocationListItem.vue
  src/lib-components/BlockMediaWithText.vue
  src/lib-components/IconWithLink.vue
  src/lib-components/SectionStaffArticleList.vue
  src/stories/SectionStaffArticleList.stories.js
Labels: bugfix

#107 fix: highlight update to match craft structure
  src/lib-components/BlockHighlight.vue
  src/lib-components/Flexible/Highlight.vue
  src/stories/Flexible_Highlight.stories.js
Labels: bugfix

#110 fix: block and flexible highlight update
  src/lib-components/Flexible/Highlight.vue
  src/stories/Flexible_Highlight.stories.js
Labels: bugfix

#115 ci: Lint PR labels and titles
  .github/workflows/lint-pr.yml
Labels: ci

#113 chore: APPS-1779 Refactor FooterSponsor to pull data from Craft
  dev/serve.vue
  src/lib-components/BlockSponsor.vue
  src/lib-components/FooterSponsor.vue
  src/lib-components/ResponsiveImage.vue
  src/lib-components/index.js
  src/stories/BlockSponsor.spec.js
  src/stories/BlockSponsor.stories.js
  src/stories/FooterSponsor.stories.js
Labels: chore

#116 feat: add footerMain
  dev/serve.vue
  src/lib-components/BlockSponsor.vue
  src/lib-components/FooterMain.vue
  src/lib-components/FooterPrimary.vue
  src/lib-components/FooterSock.vue
  src/lib-components/index.js
  src/stories/FooterMain.spec.js
  src/stories/FooterMain.stories.js
Labels: feature

#117 feat: Flexible Highlight update fields
  dev/serve.vue
  src/lib-components/BlockHighlight.vue
  src/lib-components/Flexible/Highlight.vue
  src/stories/Flexible_Highlight.stories.js
Labels: feature

#119 fix: update highlight component
  src/lib-components/BlockHighlight.vue
Labels: bugfix

#111 feat: card with image updates to match craft structure
  dev/serve.vue
  src/lib-components/BlockHighlight.vue
  src/lib-components/Flexible/CardWithImage.vue
  src/stories/Flexible_CardWithImage.stories.js
Labels: feature

#122 fix: Add focal point to responsive image
  src/lib-components/Flexible/MediaGallery/BannerImage.vue
  src/lib-components/Flexible/MediaGallery/ThumbnailCard.vue
  src/lib-components/ResponsiveImage.vue
  src/stories/MediaGallery_ThumbnailCard.stories.js
  src/stories/mock-api.json
Labels: bugfix

#121 fix: add else statement to CardWithImage and Highlight
  src/lib-components/Flexible/CardWithImage.vue
  src/lib-components/Flexible/Highlight.vue
Labels: bugfix

#123 fix: undo change to blockhighlight max-width
  src/lib-components/BlockHighlight.vue
Labels: bugfix

#118 chore: adjust banner-* and related components for qa
  dev/serve.vue
  src/lib-components/BannerFeatured.vue
  src/lib-components/BannerHeader.vue
  src/lib-components/BannerText.vue
  src/lib-components/BlockStaffDetail.vue
  src/lib-components/BlockStaffList.vue
  src/lib-components/ButtonLink.vue
  src/lib-components/FlexibleBlocks.vue
  src/lib-components/HeadingArrow.vue
  src/lib-components/IconWithLink.vue
  src/lib-components/NavSecondary.vue
  src/stories/BannerFeatured.stories.js
  src/stories/BannerText.stories.js
  src/stories/IconWithLink.stories.js
Labels: chore

#124 fix: pass wayfinder color from banner-featured to heading-arrow
  src/lib-components/BannerFeatured.vue
  src/lib-components/BannerText.vue
Labels: bugfix

#125 chore: qa of masthead secondary
  src/lib-components/MastheadSecondary.vue
Labels: chore

#126 chore: qa of nav-breadcrumb component
  src/lib-components/NavBreadcrumb.vue
  src/lib-components/NavSecondary.vue
Labels: chore

#112 feat: Refactor FlexibleBlocks
  src/lib-components/BlockHighlight.vue
  src/lib-components/BlockMediaWithText.vue
  src/lib-components/Flexible/CardWithImage.vue
  src/lib-components/Flexible/Highlight.vue
  src/lib-components/Flexible/MediaGallery.vue
  src/lib-components/Flexible/MediaWithText.vue
  src/lib-components/FlexibleBlocks.vue
  src/lib-components/MediaBadge.vue
  src/stories/BlockMediaWithText.stories.js
  src/stories/FlexibleBlocks.spec.js
  src/stories/FlexibleBlocks.stories.js
  src/stories/Flexible_AssociatedTopicCards.stories.js
  src/stories/Flexible_CallToAction.stories.js
  src/stories/Flexible_CallToAction2Up.stories.js
  src/stories/Flexible_CardWithImage.stories.js
  src/stories/Flexible_Highlight.stories.js
  src/stories/Flexible_MediaGallery.stories.js
  src/stories/Flexible_MediaWithText.stories.js
  src/stories/Flexible_RichText.stories.js
  src/stories/Flexible_SimpleCards.stories.js
  src/stories/SectionWrapper.stories.js
  src/stories/mock/BlockMediaWithText.js
  src/stories/mock/Flexible_AssociatedTopicCards.js
  src/stories/mock/Flexible_CallToAction.js
  src/stories/mock/Flexible_CallToAction2Up.js
  src/stories/mock/Flexible_CardWithImage.js
  src/stories/mock/Flexible_Highlight.js
  src/stories/mock/Flexible_MediaGallery.js
  src/stories/mock/Flexible_MediaWithText.js
  src/stories/mock/Flexible_RichText.js
  src/stories/mock/Flexible_SimpleCards.js
Labels: Ready for Review ​🎯​, feature

#128 fix: divider margins
  src/lib-components/DividerGeneral.vue
  src/lib-components/DividerWayFinder.vue
Labels: bugfix, Ready for Review ​🎯​

#129 chore: qa card with illustration components
  src/lib-components/BlockCardWithIllustration.vue
  src/lib-components/SectionCardsWithIllustrations.vue
  src/stories/SectionCardsWithIllustrations.stories.js
Labels: chore

#133 feat: meap cta variant
  src/lib-components/BlockCallToAction.vue
  src/stories/BlockCallToAction.stories.js
Labels: feature

#130 fix: Apps 1752 fix update impactnumberscarousel with responsive image and fix molecule interaction
  dev/serve.vue
  src/lib-components/BannerFeatured.vue
  src/lib-components/BannerHeader.vue
  src/lib-components/BannerText.vue
  src/lib-components/ImpactNumbersCarousel.vue
  src/stories/Flexible_ImpactNumbersCarousel.stories.js
  src/stories/ImpactNumbersCarousel.stories.js
Labels: enhancement, Ready for Review ​🎯​

#135 ci: Add storybook deploy on push to main
  .github/workflows/ci.yml
Labels: ci

#134 chore: qa of simple cards
  src/lib-components/BlockSimpleCard.vue
  src/lib-components/SimpleCards.vue
  src/stories/SimpleCards.stories.js
Labels: chore

#137 fix: media gallery component
  build/rollup.config.js
  src/lib-components/Flexible/MediaGallery.vue
  src/lib-components/Flexible/MediaGallery/BannerImage.vue
  src/lib-components/Flexible/MediaGallery/NewLightbox.vue
  src/lib-components/Flexible/MediaGallery/ThumbnailCard.vue
  src/lib-components/MediaBadge.vue
Labels: bugfix, chore

#140 fix: move vue-glide css to global
  src/lib-components/Flexible/MediaGallery/NewLightbox.vue
  src/lib-components/index.js
Labels: bugfix

#138 chore: News index updates to BannerHeader and SectionTeaserHighlight
  src/lib-components/BannerHeader.vue
  src/lib-components/SectionTeaserHighlight.vue
  src/stories/BannerHeader.stories.js
Labels: chore

#141 fix: copy vue-glide css into new lightbox
  build/rollup.config.js
  src/lib-components/Flexible/MediaGallery/NewLightbox.vue
  src/lib-components/index.js
Labels: bugfix

#144 fix: APPS-1772 fix section title and section summary
  dev/serve.vue
  src/lib-components/Flexible/ImpactNumbersCarousel.vue
  src/lib-components/Flexible/MediaGallery.vue
  src/lib-components/Flexible/MediaGallery/BannerImage.vue
  src/lib-components/Flexible/MediaGallery/ThumbnailCard.vue
  src/lib-components/Flexible/RichText.vue
  src/lib-components/MastheadSecondary.vue
  src/lib-components/SectionCardsWithIllustrations.vue
  src/stories/Flexible_ImpactNumbersCarousel.stories.js
  src/stories/mock-api.json
  src/stories/mock/Flexible_MediaGallery.js
  src/stories/mock/Flexible_RichText.js
Labels: bugfix

#145 chore: qa of components used in meap project detail
  src/lib-components/BannerHeader.vue
  src/lib-components/BannerText.vue
  src/lib-components/Flexible/MediaGallery.vue
  src/lib-components/Flexible/MediaGallery/ThumbnailCard.vue
  src/lib-components/Flexible/RichText.vue
  src/lib-components/FlexibleBlocks.vue
  src/lib-components/RichText.vue
  src/lib-components/SectionWrapper.vue
Labels: chore

#143 fix: qa of highlight and card with image
  src/lib-components/BlockHighlight.vue
  src/lib-components/Flexible/CardWithImage.vue
  src/lib-components/Flexible/Highlight.vue
  src/lib-components/SectionTeaserCard.vue
  src/lib-components/SectionTeaserHighlight.vue
Labels: bugfix

#147 fix: SectionWrapper child component margins
  src/lib-components/SectionWrapper.vue
Labels: bugfix

#148 fix: Fix nav
  src/lib-components/HeaderMainResponsive.vue
  src/lib-components/HeaderSmart.vue
  src/lib-components/NavMenuItem.vue
  src/lib-components/NavMenuItemResponsive.vue
  src/lib-components/NavPrimary.vue
  src/lib-components/NavSecondary.vue
  src/stories/NavMenuItemResponsive.spec.js
  src/stories/NavMenuItemResponsive.stories.js
Labels: bugfix

#149 fix: APPS-1830 pull caption title and caption text into media gallery lightbox
  dev/serve.vue
  src/lib-components/Flexible/MediaGallery/NewLightbox.vue
Labels: bugfix

#150 fix: standardize section titles
  src/lib-components/BannerHeader.vue
  src/lib-components/BannerText.vue
  src/lib-components/BlockHighlight.vue
  src/lib-components/Flexible/CardWithImage.vue
  src/lib-components/Flexible/Highlight.vue
  src/lib-components/Flexible/ImpactNumbersCarousel.vue
  src/lib-components/Flexible/MediaGallery.vue
  src/lib-components/Flexible/MediaWithText.vue
  src/lib-components/SectionWrapper.vue
  src/lib-components/SimpleCards.vue
Labels: bugfix

#151 fix: standardize section header
  src/lib-components/SectionCardsWithIllustrations.vue
Labels: bugfix

#152 fix: associated topics fpb paths
  src/lib-components/Flexible/AssociatedTopicCards.vue
  src/lib-components/Flexible/Highlight.vue
  src/stories/mock/Flexible_AssociatedTopicCards.js
Labels: bugfix

#153 fix: update flexible simple cards path
  src/lib-components/Flexible/SimpleCards.vue
  src/stories/mock/Flexible_SimpleCards.js
Labels: bugfix

#154 fix: updates tokens and clickable area on cards
  package-lock.json
  package.json
  src/lib-components/BlockHighlight.vue
  src/lib-components/BlockSimpleCard.vue
  src/lib-components/FooterPrimary.vue
  src/lib-components/FooterSock.vue
  src/lib-components/HeaderMainResponsive.vue
  src/lib-components/NavMenuItemResponsive.vue
Labels: bugfix, Ready for Review ​🎯​

#156 fix: make entire card with illustration clickable
  src/lib-components/BlockCardWithIllustration.vue
Labels: bugfix

#155 feat: adds development text to footer-sponsor
  src/lib-components/FlexibleBlocks.vue
  src/lib-components/FooterSponsor.vue
Labels: feature

#159 fix: update FlexibleCardWithImage url logic
  src/lib-components/Flexible/BannerFeatured.vue
  src/lib-components/Flexible/CardWithImage.vue
  src/lib-components/Flexible/Highlight.vue
Labels: bugfix

#160 fix: replace p tag with div and replace v-html to v-text in some cases
  src/lib-components/BlockHighlight.vue
  src/lib-components/BlockSpaces.vue
  src/lib-components/IconWithLink.vue
  src/lib-components/SectionWrapper.vue
Labels: refactor

#158 fix: Sponsor footer layout
  src/lib-components/BlockSponsor.vue
  src/lib-components/FooterSponsor.vue
Labels: bugfix, Ready for Review ​🎯​

#161 fix: v-text to v-html
  src/lib-components/BlockHighlight.vue
  src/stories/BlockHighlight.stories.js
Labels: bugfix

#162 fix: block-highlight & spaces
  dev/serve.vue
  src/lib-components/BlockSpaces.vue
  src/stories/BlockHighlight.stories.js
  src/stories/BlockSpaces.stories.js
Labels: bugfix

#163 fix: updates responsive width of BlockHighlight for card variation
  src/lib-components/BlockHighlight.vue
Labels: bugfix, Ready for Review ​🎯​

#164 fix: various tweaks to components
  src/lib-components/BannerFeatured.vue
  src/lib-components/BannerHeader.vue
  src/lib-components/BlockCallToAction.vue
  src/lib-components/BlockCardWithIllustration.vue
  src/lib-components/BlockHighlight.vue
  src/lib-components/BlockSimpleCard.vue
  src/lib-components/BlockSponsor.vue
  src/lib-components/BlockStaffArticleList.vue
  src/lib-components/Flexible/CallToAction.vue
  src/lib-components/Flexible/CardWithImage.vue
  src/lib-components/Flexible/MediaGallery/NewLightbox.vue
  src/lib-components/FooterPrimary.vue
  src/lib-components/FooterSponsor.vue
  src/lib-components/HeaderMainResponsive.vue
  src/lib-components/SectionStaffArticleList.vue
  src/lib-components/SectionTeaserCard.vue
  src/lib-components/SectionTeaserHighlight.vue
  src/lib-components/SectionTeaserList.vue
  src/lib-components/SimpleCards.vue
  src/lib-components/SiteBrandBar.vue
Labels: bugfix

#165 fix: keyboard tab key use and acronym
  src/lib-components/HeaderMainResponsive.vue
  src/lib-components/NavMenuItem.vue
  src/lib-components/NavMenuItemResponsive.vue
  src/lib-components/NavPrimary.vue
  src/lib-components/NavSecondary.vue
  src/stories/HeaderMainResponsive.stories.js
  src/stories/NavPrimary.stories.js
Labels: bugfix

#166 fix: adjust focus styling, spacing, remove h1 from site name
  src/lib-components/HeaderMainResponsive.vue
  src/lib-components/NavMenuItem.vue
  src/lib-components/NavMenuItemResponsive.vue
  src/lib-components/NavPrimary.vue
Labels: bugfix

#167 fix: adjust spacing to banners
  src/lib-components/BannerFeatured.vue
  src/lib-components/BannerHeader.vue
Labels: bugfix

#168 fix: Simple cards data manipulation
  src/lib-components/Flexible/SimpleCards.vue
  src/stories/mock/Flexible_SimpleCards.js
Labels: bugfix

#170 fix: refactor text truncation to use tokens
  package-lock.json
  package.json
  src/lib-components/BlockCardWithIllustration.vue
  src/lib-components/BlockHighlight.vue
  src/lib-components/BlockSimpleCard.vue
  src/lib-components/BlockStaffArticleList.vue
  src/lib-components/GridGallery.vue
  src/lib-components/NavBreadcrumb.vue
Labels: chore

#171 fix: mobile spacing for banner featured and header
  src/lib-components/BannerFeatured.vue
  src/lib-components/BannerHeader.vue
  src/lib-components/SectionStaffArticleList.vue
  src/lib-components/SectionTeaserHighlight.vue
Labels: bugfix

#172 fix: udpates BannerText spacing
  src/lib-components/BannerText.vue
Labels: bugfix

#174 fix: QA navbreadcrumb
  src/lib-components/NavBreadcrumb.vue
  src/mixins/getMeapParentPageTitle.js
  src/mixins/getParentPageTitle.js
  src/mixins/getParentPageUrl.js
Labels: bugfix

#175 fix: show submenu items on focus
  src/lib-components/NavMenuItem.vue
  src/lib-components/NavPrimary.vue
Labels: bugfix

#176 fix: responsive styling for BlockHiglight, CTA, CardWithImage,
  src/lib-components/BlockCallToAction.vue
  src/lib-components/BlockHighlight.vue
  src/lib-components/Flexible/CardWithImage.vue
  src/lib-components/Flexible/Highlight.vue
Labels: bugfix

#177 fix: update mixin
  src/mixins/getParentPageUrl.js
Labels: bugfix

#169 fix: updates FooterSponsor spacing
  src/lib-components/FooterSponsor.vue
Labels: bugfix
