Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2022-11, with the labels that each got.

#227 feat: adds max-height to responsive-video in BannerHeader and BannerF…
  src/lib-components/BannerFeatured.vue
  src/lib-components/BannerHeader.vue
Labels: feature

#229 fix: APPS-2010
  src/lib-components/FlexibleBlocks.vue
  src/lib-components/SearchGeneric.vue
Labels: fix

#225 feat: SearchResult component
  src/lib-components/SearchResult.vue
  src/lib-components/index.js
  src/stories/SearchResult.spec.js
  src/stories/SearchResult.stories.js
Labels: feature

#230 fix: section wrapper cta styling and color theme of cards with illustrations
  src/lib-components/BlockCardWithIllustration.vue
  src/lib-components/SectionWrapper.vue
Labels: fix

#228 feat: update table styling
  src/lib-components/BlockSpaces.vue
  src/lib-components/BlockStaffDetail.vue
  src/lib-components/RichText.vue
  src/lib-components/SectionSpacesList.vue
Labels: feature

#232 fix: add molecule svg with blue background when there is no event image prop for blockhighlight
  src/lib-components/BlockHighlight.vue
  src/stories/BlockHighlight.stories.js
Labels: enhancement

#233 feat: Add subject area to banner text and header
  src/lib-components/BannerHeader.vue
  src/lib-components/BannerText.vue
  src/lib-components/BlockStaffArticleList.vue
  src/stories/BannerHeader.stories.js
  src/stories/BannerText.stories.js
Labels: feature

#234 fix: Impact Report home page cannot be a nuxt link on drupal environment
  src/lib-components/NavPrimary.vue
  src/stories/NavPrimary.stories.js
Labels: bugfix

#235 fix: don't use `?.` operator in MediaItem
  src/lib-components/Media/Item.vue
Labels: bugfix, fix

#236 fix: updates responsive image and gallery caption
  src/lib-components/Flexible/MediaGallery/ThumbnailCard.vue
  src/lib-components/ResponsiveImage.vue
Labels: fix

#237 fix: update searchhome
  src/lib-components/SearchHome.vue
Labels: bugfix

#238 feat: updates recent bugs and QA
  src/lib-components/BannerFeatured.vue
  src/lib-components/BannerHeader.vue
  src/lib-components/BannerText.vue
  src/lib-components/BlockHighlight.vue
  src/lib-components/BlockStaffDetail.vue
  src/lib-components/DividerWayFinder.vue
Labels: feature

#239 fix: update all router-links to smart-links
  src/lib-components/BlockEvent.vue
  src/lib-components/BlockHighlight.vue
  src/lib-components/BlockLocationListItem.vue
  src/lib-components/BlockPostSmall.vue
  src/lib-components/BlockStaffArticleList.vue
  src/lib-components/BlockStaffList.vue
  src/lib-components/FooterPrimary.vue
  src/lib-components/HeaderMainResponsive.vue
  src/lib-components/NavBreadcrumb.vue
  src/lib-components/NavPrimary.vue
  src/lib-components/SectionCardsWithIllustrations.vue
  src/lib-components/SectionDualMasonry.vue
  src/lib-components/SectionPagination.vue
  src/lib-components/SectionPostSmall.vue
Labels: fix

#240 fix: support embeds in MediaGalleryBannerImage
  src/lib-components/Flexible/MediaGallery.vue
  src/lib-components/Flexible/MediaGallery/BannerImage.vue
Labels: bugfix, fix

#241 feat: APSS-2040 Sync route queries
  src/lib-components/SearchGeneric.vue
  src/stories/SearchGeneric.stories.js
Labels: feature

#242 fix: update fpbs for images
  src/lib-components/Flexible/CardWithImage.vue
  src/lib-components/Flexible/Highlight.vue
Labels: bugfix

#243 feat: ModalLightbox component
  src/lib-components/FlexibleBlocks.vue
  src/lib-components/ModalLightbox.vue
  src/stories/ModalLightbox.spec.js
  src/stories/ModalLightbox.stories.js
Labels: enhancement, feature

#244 feat: APPS-2073 added spec file storybook file and component file
  src/lib-components/BlockGenericList.vue
  src/stories/BlockGenericList.spec.js
  src/stories/BlockGenericList.stories.js
Labels: feature

#246 fix: Move search icon to right of the input text and add hover behavior
  src/lib-components/SearchGeneric.vue
Labels: bugfix

#247 feat: APPS-2074 create a section location list component
  src/lib-components/BlockLocationListItem.vue
  src/lib-components/SectionLocationList.vue
  src/lib-components/index.js
  src/stories/BlockLocationListItem.stories.js
  src/stories/SectionLocationList.spec.js
  src/stories/SectionLocationList.stories.js
Labels: feature

#245 feat: VideoJS and Audio
  build/rollup.config.js
  package-lock.json
  package.json
  src/lib-components/Media/Item.vue
  src/lib-components/Media/VideoJs.vue
  src/stories/MediaItem.stories.js
Labels: feature

#249 feat: APPS-2075 Create Section for GenericList
  src/lib-components/BlockGenericList.vue
  src/lib-components/SectionGenericList.vue
  src/lib-components/index.js
  src/stories/BlockGenericList.stories.js
  src/stories/SectionGenericList.stories.js
Labels: feature, Work in progress / Draft ✍

#250 fix: rename search_site to search-site
  src/lib-components/SearchHome.vue
Labels: bugfix

#251 fix: keyup has a jarring effect so switching to change
  src/lib-components/SearchGeneric.vue
Labels: fix

#252 fix: prefix location link with forward slash
  src/lib-components/BannerFeatured.vue
  src/lib-components/BlockGenericList.vue
  src/lib-components/BlockHighlight.vue
  src/lib-components/BlockStaffDetail.vue
Labels: fix

#248 feat: Apps-2013 selected search filters
  src/lib-components/BlockSearchFilter.vue
  src/lib-components/SectionSearchFilter.vue
  src/stories/BlockSearchFilter.spec.js
  src/stories/BlockSearchFilter.stories.js
  src/stories/SectionSearchFilter.spec.js
  src/stories/SectionSearchFilter.stories.js
Labels: feature

#256 fix: Fix search generic
  src/lib-components/SearchGeneric.vue
Labels: bugfix

#257 fix: add payRate to GenericList
  src/lib-components/BlockGenericList.vue
  src/lib-components/SectionGenericList.vue
  src/stories/SectionGenericList.stories.js
Labels: fix

#253 fix: ux component qa
  src/lib-components/BannerText.vue
  src/lib-components/BlockStaffList.vue
  src/lib-components/FlexibleBlocks.vue
  src/lib-components/ImpactNumbersCarousel.vue
  src/lib-components/SectionDualMasonry.vue
Labels: feature

#255 feat: APPS-1597 block location list update
  .env
  .env.example
  src/lib-components/BlockGenericList.vue
  src/lib-components/BlockLocationListItem.vue
  src/lib-components/SearchGeneric.vue
  src/stories/BlockForm.stories.js
  src/stories/BlockLocationListItem.stories.js
  src/stories/SectionLocationList.stories.js
Labels: feature

#261 fix: revert outside click using focusout
  src/lib-components/SearchGeneric.vue
Labels: bugfix

#254 feat!: MediaWithText A/V, lightbox
  dev/serve.vue
  src/lib-components/BlockMediaWithText.vue
  src/lib-components/Flexible/MediaGallery/NewLightbox.vue
  src/lib-components/Flexible/MediaWithText.vue
  src/lib-components/Media/Item.vue
  src/stories/BlockMediaWithText.stories.js
  src/stories/MediaGallery_NewLightbox.spec.js
  src/stories/MediaGallery_NewLightbox.stories.js
  src/stories/SectionWrapper.stories.js
  src/stories/mock/BlockMediaWithText.js
Labels: feature, breaking

#263 fix: Update README.md
  README.md
Labels: fix

#260 fix: updates from qa of news listing template
  src/lib-components/BannerFeatured.vue
  src/lib-components/BlockHighlight.vue
  src/lib-components/BlockStaffArticleList.vue
  src/lib-components/HeaderMainResponsive.vue
  src/lib-components/MastheadSecondary.vue
  src/lib-components/SearchGeneric.vue
  src/lib-components/SectionStaffArticleList.vue
  src/lib-components/SectionWrapper.vue
  src/lib-components/SiteBrandBar.vue
Labels: Work in progress / Draft ✍, fix

#262 fix: Update Amenities on LocationLists
  src/lib-components/BlockLocationListItem.vue
  src/lib-components/IconWithLink.vue
  src/stories/BlockLocationListItem.stories.js
  src/stories/SectionLocationList.stories.js
Labels: fix
