Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2023-01, with the labels that each got.

#292 fix: remove margin in block hours component
  .github/workflows/ci.yml
  .github/workflows/percy.yml
  cypress.json
  src/lib-components/BlockHours.vue
Labels: fix

#290 feat: APPS-2510 Strip html tags and truncate summary text on various components
  src/lib-components/BlockCardWithIllustration.vue
  src/lib-components/BlockGenericList.vue
  src/lib-components/BlockHighlight.vue
  src/lib-components/BlockSimpleCard.vue
  src/lib-components/BlockStaffArticleList.vue
  src/lib-components/Flexible/MediaGallery/ThumbnailCard.vue
  src/lib-components/SearchResult.vue
  src/mixins/removeHtmlTruncate.js
  src/stories/BlockCardWithIllustration.stories.js
  src/stories/BlockHighlight.stories.js
  src/stories/BlockSimpleCard.stories.js
  src/stories/BlockStaffArticleList.stories.js
  src/stories/SectionCardsWithIllustrations.stories.js
  src/stories/SectionStaffArticleList.stories.js
  src/stories/SimpleCards.stories.js
  src/stories/mock/Media.js
Labels: feature

#291 feat: APPS-2111 update search home to search primo
  src/lib-components/SearchHome.vue
  src/stories/SearchHome.spec.js
  src/stories/SearchHome.stories.js
Labels: feature

#294 fix: update computed properties
  src/lib-components/BlockCardWithIllustration.vue
  src/lib-components/BlockGenericList.vue
  src/lib-components/BlockHighlight.vue
  src/lib-components/BlockSimpleCard.vue
  src/lib-components/BlockStaffArticleList.vue
  src/lib-components/Flexible/MediaGallery/ThumbnailCard.vue
  src/lib-components/SearchResult.vue
  src/stories/BlockCardWithIllustration.stories.js
  src/stories/Flexible_AssociatedTopicCards.stories.js
  src/stories/Flexible_CardWithImage.stories.js
  src/stories/mock/Flexible_AssociatedTopicCards.js
Labels: bugfix

#293 fix: APPS-2123 strip craft url
  src/lib-components/RichText.vue
  src/mixins/stripCraftURLFromText.js
  src/store/modules/footerSponsor.js
  src/stories/BlockSponsor.stories.js
  src/stories/Flexible_BannerFeatured.stories.js
  src/stories/Flexible_GridGalleryCards.stories.js
  src/stories/Flexible_RichText.stories.js
  src/stories/FooterMain.stories.js
  src/stories/FooterSponsor.stories.js
  src/stories/MediaGallery_ThumbnailCard.stories.js
  src/stories/RichText.stories.js
  src/stories/mock/BlockMediaWithText.js
  src/stories/mock/Flexible_CardWithImage.js
  src/stories/mock/Flexible_Highlight.js
  src/stories/mock/Flexible_MediaWithText.js
  src/stories/mock/Flexible_RichText.js
  src/stories/mock/Media.js
Labels: bugfix

#295 fix: Fix html tag display on cards-with-illustration
  src/lib-components/BlockCardWithIllustration.vue
  src/lib-components/SearchHome.vue
  src/mixins/removeHtmlTruncate.js
  src/stories/BlockCardWithIllustration.stories.js
Labels: bugfix

#289 fix: APPS 2084 Allow components to only display dates and not show time
  .github/workflows/ci.yml
  cypress.json
  package-lock.json
  package.json
  src/lib-components/BannerFeatured.vue
  src/lib-components/BannerHeader.vue
  src/lib-components/BannerText.vue
  src/lib-components/BlockEvent.vue
  src/lib-components/BlockHighlight.vue
  src/lib-components/Flexible/BannerFeatured.vue
  src/lib-components/Flexible/CardWithImage.vue
  src/lib-components/SectionDualMasonry.vue
  src/lib-components/SectionTeaserCard.vue
  src/lib-components/SectionTeaserHighlight.vue
  src/lib-components/SectionTeaserList.vue
  src/stories/BannerFeatured.stories.js
  src/stories/BannerHeader.stories.js
  src/stories/BannerText.stories.js
  src/stories/BlockEvent.stories.js
  src/stories/BlockHighlight.stories.js
  src/stories/Flexible_BannerFeatured.stories.js
  src/stories/SectionTeaserCard.stories.js
  src/stories/SectionTeaserHighlight.stories.js
  src/stories/SectionTeaserList.stories.js
  src/stories/mock-api.json
  src/stories/mock/Flexible_CardWithImage.js
Labels: bugfix

#297 fix: removeHtmlTruncate unescape HTML entities
  src/mixins/removeHtmlTruncate.js
Labels: fix

#296 feat: APPS-2048 create academic departments table component
  src/lib-components/BlockStaffList.vue
  src/lib-components/BlockStaffSubjectLibrarian.vue
  src/lib-components/SectionStaffSubjectLibrarian.vue
  src/lib-components/index.js
  src/stories/BlockStaffList.stories.js
  src/stories/BlockStaffSubjectLibrarian.spec.js
  src/stories/BlockStaffSubjectLibrarian.stories.js
  src/stories/SectionStaffSubjectLibrarian.spec.js
  src/stories/SectionStaffSubjectLibrarian.stories.js
Labels: feature

#300 fix: APPS-2009 add null check
  src/lib-components/BlockCardWithIllustration.vue
  src/mixins/removeHtmlTruncate.js
Labels: fix

#298 fix: SectionTeaserCard alternativeName
  src/lib-components/SectionTeaserCard.vue
Labels: fix

#299 fix: link URL in BlockCallToAction
  src/stories/mock/Flexible_CallToAction.js
Labels: fix

#302 fix: revert null check
  src/lib-components/BlockCardWithIllustration.vue
  src/mixins/removeHtmlTruncate.js
Labels: bugfix

#303 feat: APPS-2121 add title to iframes labeling the content in the iframe
  src/lib-components/BlockHours.vue
Labels: feature

#305 fix: APPS-2141 Fix print svg and text in Block Amenities
  .env
  .gitignore
  src/lib-components/BlockAmenities.vue
Labels: fix

#306 fix: hydration errors
  src/lib-components/BlockStaffList.vue
  src/lib-components/BlockStaffSubjectLibrarian.vue
  src/lib-components/FooterPrimary.vue
  src/lib-components/SearchGeneric.vue
  src/lib-components/SearchGenericFilterButtons.vue
  src/lib-components/SectionStaffSubjectLibrarian.vue
Labels: bugfix

#307 fix: Fix hydration part2
  src/lib-components/BlockAmenities.vue
  src/lib-components/BlockEvent.vue
  src/lib-components/BlockGenericList.vue
  src/lib-components/BlockLocationListItem.vue
  src/lib-components/BlockSimpleCard.vue
  src/lib-components/BlockStaffDetail.vue
  src/lib-components/BlockStaffList.vue
  src/lib-components/BlockStaffSubjectLibrarian.vue
  src/lib-components/GridGallery.vue
  src/lib-components/SearchGeneric.vue
  src/lib-components/SectionStaffSubjectLibrarian.vue
  src/lib-components/SectionWrapper.vue
  src/lib-components/StoryWithImage.vue
Labels: bugfix

#308 fix: Add remove filters back
  src/lib-components/SearchGeneric.vue
Labels: bugfix

#309 Revert "fix: Add remove filters back"
  src/lib-components/SearchGeneric.vue
Labels: bugfix

#310 fix: Add click-outside directive back
  src/lib-components/SearchGeneric.vue
Labels: bugfix

#312 fix: Refactor date time for flexible_Banner* components and Fix category null display in BlockHighlight
  src/lib-components/Flexible/BannerFeatured.vue
  src/lib-components/Flexible/CardWithImage.vue
  src/lib-components/Flexible/Highlight.vue
  src/stories/Flexible_BannerFeatured.stories.js
  src/stories/Flexible_CardWithImage.stories.js
  src/stories/Flexible_Highlight.stories.js
  src/stories/mock/Flexible_Highlight.js
Labels: bugfix

#311 feat: add ongoing prop to block highlight
  src/lib-components/BlockHighlight.vue
  src/lib-components/Flexible/CardWithImage.vue
  src/lib-components/Flexible/Highlight.vue
  src/lib-components/SectionTeaserCard.vue
  src/lib-components/SectionTeaserHighlight.vue
  src/lib-components/SectionTeaserList.vue
  src/stories/BlockHighlight.stories.js
  src/stories/SectionTeaserHighlight.stories.js
  src/stories/SectionTeaserList.stories.js
Labels: feature

#313 fix: remove v-if to v-show and add null check and use replace all
  src/lib-components/SearchGeneric.vue
  src/lib-components/SectionRemoveSearchFilter.vue
  src/mixins/removeHtmlTruncate.js
  src/mixins/stripCraftURLFromText.js
Labels: bugfix

#314 fix: update location list hours
  src/lib-components/BlockLocationListItem.vue
  src/lib-components/SectionLocationList.vue
  src/stories/BlockLocationListItem.stories.js
  src/stories/SectionLocationList.stories.js
Labels: bugfix

#304 fix: APPS-1757 fix auto height of form
  src/lib-components/Flexible/Form.vue
Labels: fix

#315 feat: media gallery credit and link
  src/lib-components/Flexible/MediaGallery/NewLightbox.vue
  src/lib-components/Flexible/MediaGallery/ThumbnailCard.vue
  src/stories/MediaGallery_ThumbnailCard.stories.js
  src/stories/mock/Media.js
Labels: feature

#318 fix: use consistent border and spacing for blockHours
  src/lib-components/BlockHours.vue
Labels: fix

#317 refactor: APPS-1920 refactor external links
  src/lib-components/RichText.vue
  src/mixins/accessibleExternalLinks.js
  src/stories/RichText.stories.js
Labels: refactor

#320 fix: remove slash in mailto links and update phones to use tel
  src/lib-components/BannerText.vue
  src/lib-components/BlockStaffDetail.vue
  src/lib-components/BlockStaffList.vue
  src/lib-components/BlockStaffSubjectLibrarian.vue
  src/stories/BlockCallToAction.stories.js
Labels: fix

#319 fix: video embed display
  src/lib-components/Media/Item.vue
  src/stories/mock/Media.js
Labels: bugfix
