Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2023-09, with the labels that each got.

#386 fix: release vue3.x to next channel
  CHANGELOG.md
  package.json
Labels: bugfix

#387 feat: bump up semantic minor version test
  CHANGELOG.md
  package.json
  pnpm-lock.yaml
Labels: feature

#389 Bump version to 2.40.0-vue3.x.1
  package.json
Labels: fix

#390 feat: fix and use alpha release
  package.json
  release.config.js
Labels: feature

#391 feat: test minor bump with semantic pre release alpha
  README.md
Labels: feature

#392 feat: test patch bump with semantic pre release alpha
  README.md
Labels: fix

#395 feat: Add SiteNotificationAlert, RichText, ButtonLink, and Smart Link components
  .storybook/main.ts
  .storybook/preview.ts
  dev/serve.css
  dev/serve.js
  dev/serve.vue
  package.json
  pnpm-lock.yaml
  src/App.vue
  src/components/index.js
  src/composables/accessibleExternalLinks.js
  src/composables/formatLinkTarget.js
  src/composables/isInternalLink.js
  src/composables/isRelativeLink.js
  src/composables/stripCraftURLFromText.js
  src/entry.js
  src/lib-components/ButtonLink.vue
  src/lib-components/DividerGeneral.vue
  src/lib-components/DividerWayFinder.vue
  src/lib-components/HelloWorld.vue
  src/lib-components/RichText.vue
  src/lib-components/SiteNotificationAlert.vue
  src/lib-components/SmartLink.vue
  src/lib-components/index.js
  src/stories/ButtonLink.spec.js
  src/stories/ButtonLink.stories.js
  src/stories/DividerGeneral.stories.js
  src/stories/DividerWayFinder.stories.js
  src/stories/RichText.spec.js
  src/stories/RichText.stories.js
  src/stories/SiteNotificationAlert.spec.js
  src/stories/SiteNotificationAlert.stories.js
  src/stories/SmartLink.spec.js
  src/stories/SmartLink.stories.js
  src/stories/mock-api.json
  src/stories/mocks/vue-router.mock.js
  vite.config.serve.ts
  vite.config.ts
Labels: feature

#394 feat: APPS-1932 create media gallery half width
  src/lib-components/Flexible/MediaGallery.vue
  src/lib-components/Flexible/MediaGallery/BannerImage.vue
  src/lib-components/FlexibleBlocks.vue
  src/lib-components/SearchGeneric.vue
  src/lib-components/SectionWrapper.vue
  src/stories/FlexibleBlocks.stories.js
  src/stories/Flexible_MediaGallery.stories.js
  src/stories/MediaGallery.spec.js
  src/stories/mock/Media.js
Labels: feature

#396 feat: ButtonHide
  .storybook/main.ts
  package.json
  pnpm-lock.yaml
  serve/index.html
  serve/serve.css
  serve/serve.js
  serve/serve.vue
  src/App.vue
  src/lib-components/ButtonHide.vue
  src/lib-components/DividerWayFinder.vue
  src/lib-components/RichText.vue
  src/lib-components/index.js
  src/stories/ButtonHide.spec.js
  src/stories/ButtonHide.stories.js
  src/stories/ButtonLink.stories.js
  src/stories/DividerWayFinder.stories.js
  src/stories/RichText.stories.js
  src/stories/SiteNotificationAlert.stories.js
  src/stories/SmartLink.stories.js
  vite.config.serve.ts
  vite.config.ts
Labels: feature

#397 feat: update styles to work with halfWidth option in redactor
  src/lib-components/RichText.vue
Labels: feature

#398 feat: ButtonShow, ButtonMore
  serve/serve.vue
  src/App.vue
  src/lib-components/ButtonMore.vue
  src/lib-components/ButtonShow.vue
  src/lib-components/index.js
  src/stories/ButtonMore.spec.js
  src/stories/ButtonMore.stories.js
  src/stories/ButtonShow.spec.js
  src/stories/ButtonShow.stories.js
  vite.config.serve.ts
  vite.config.ts
Labels: feature

#399 feat: Add heading-arrow component
  serve/serve.vue
  src/App.vue
  src/lib-components/HeadingArrow.vue
  src/lib-components/index.js
  src/stories/HeadingArrow.spec.js
  src/stories/HeadingArrow.stories.js
Labels: feature

#400 feat: add SiteBrandBar, IconWithLink, PullQuote, BlockDate components
  serve/serve.vue
  src/App.vue
  src/lib-components/BlockDate.vue
  src/lib-components/IconWithLink.vue
  src/lib-components/PullQuote.vue
  src/lib-components/SiteBrandBar.vue
  src/lib-components/index.js
  src/stories/BlockDate.spec.js
  src/stories/BlockDate.stories.js
  src/stories/IconWithLink.spec.js
  src/stories/IconWithLink.stories.js
  src/stories/PullQuote.spec.js
  src/stories/PullQuote.stories.js
  src/stories/SiteBrandBar.spec.js
  src/stories/SiteBrandBar.stories.js
Labels: feature

#401 feat: "Include past events" single checkbox filter
  src/lib-components/SectionRemoveSearchFilter.vue
  src/stories/SearchGeneric.stories.js
Labels: feature
