Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2023-10, with the labels that each got.

#405 feat: add AlphaBrowseBy, BlockCTA, BlockCTA2Up, SearchResult, SingleCheckbox components
  cypress.config.ts
  package.json
  pnpm-lock.yaml
  serve/serve.css
  serve/serve.vue
  src/App.vue
  src/lib-components/AlphabeticalBrowseBy.vue
  src/lib-components/BlockCallToAction.vue
  src/lib-components/BlockCallToActionTwoUp.vue
  src/lib-components/BlockMediaWithText.vue
  src/lib-components/SearchResult.vue
  src/lib-components/SingleCheckbox.vue
  src/lib-components/index.js
  src/stories/AlphabeticalBrowseBy.spec.js
  src/stories/AlphabeticalBrowseBy.stories.js
  src/stories/BlockCallToAction.spec.js
  src/stories/BlockCallToAction.stories.js
  src/stories/BlockCallToActionTwoUp.spec.js
  src/stories/BlockCallToActionTwoUp.stories.js
  src/stories/IconWithLink.stories.js
  src/stories/MediaItem.stories.js
  src/stories/SearchResult.spec.js
  src/stories/SearchResult.stories.js
  src/stories/SingleCheckbox.spec.js
  src/stories/SingleCheckbox.stories.js
  src/style.css
  src/utils/removeHtmlTruncate.js
Labels: feature

#406 feat: Apps 2431 apps 2454 add pinia
  .github/workflows/percy.yml
  .storybook/preview.ts
  package.json
  pnpm-lock.yaml
  src/lib-components/BlockCallToAction.vue
  src/lib-components/ButtonLink.vue
  src/stores/GlobalStore.js
  src/stores/mock.js
  src/stories/BlockCallToAction.stories.js
Labels: feature

#408 feat: APPS-2405 Add footer components and get footer data from mock pinia store
  serve/serve.js
  serve/serve.vue
  src/App.vue
  src/composables/isInternalLink.js
  src/lib-components/BlockSponsor.vue
  src/lib-components/ButtonLink.vue
  src/lib-components/FooterMain.vue
  src/lib-components/FooterPrimary.vue
  src/lib-components/FooterSock.vue
  src/lib-components/FooterSponsor.vue
  src/lib-components/RichText.vue
  src/lib-components/SmartLink.vue
  src/lib-components/index.js
  src/main.ts
  src/stores/GlobalStore.js
  src/stores/mock.js
  src/stories/BlockSponsor.spec.js
  src/stories/BlockSponsor.stories.js
  src/stories/FooterMain.spec.js
  src/stories/FooterMain.stories.js
  src/stories/FooterPrimary.spec.js
  src/stories/FooterPrimary.stories.js
  src/stories/FooterSock.spec.js
  src/stories/FooterSock.stories.js
  src/stories/FooterSponsor.spec.js
  src/stories/FooterSponsor.stories.js
  src/utils/accessibleExternalLinks.js
  src/utils/formatLinkTarget.js
  src/utils/isInternalLink.js
  src/utils/isRelativeLink.js
  src/utils/stripCraftURLFromText.js
Labels: feature

#409 feat: APPS-2450 Add multiple block components
  package.json
  pnpm-lock.yaml
  serve/serve.vue
  src/App.vue
  src/lib-components/BlockCardWithIllustration.vue
  src/lib-components/BlockEvent.vue
  src/lib-components/BlockSimpleCard.vue
  src/lib-components/BlockSpaces.vue
  src/lib-components/BlockSponsor.vue
  src/lib-components/index.js
  src/stories/BlockCardWithIllustration.spec.js
  src/stories/BlockCardWithIllustration.stories.js
  src/stories/BlockEvent.spec.js
  src/stories/BlockEvent.stories.js
  src/stories/BlockSimpleCard.spec.js
  src/stories/BlockSimpleCard.stories.js
  src/stories/BlockSpaces.spec.js
  src/stories/BlockSpaces.stories.js
  src/utils/formatEventDates.js
  src/utils/formatEventTimes.js
  src/utils/isInternalLink.js
Labels: feature

#410 feat: APPS 2452 Add BlockShowHide, NavBreadcrumb, OrcidPub components
  serve/serve.vue
  src/App.vue
  src/lib-components/BlockShowHide.vue
  src/lib-components/NavBreadcrumb.vue
  src/lib-components/SectionStaffOrcidPublications.vue
  src/lib-components/index.js
  src/stories/BlockShowHide.spec.js
  src/stories/BlockShowHide.stories.js
  src/stories/NavBreadcrumb.spec.js
  src/stories/NavBreadcrumb.stories.js
  src/stories/SectionStaffOrcidPublications.spec.js
  src/stories/SectionStaffOrcidPublications.stories.js
Labels: feature

#411 fix: various accessibility issues
  src/lib-components/BlockEvent.vue
  src/lib-components/Flexible/Form.vue
  src/lib-components/ImpactNumbersCarousel.vue
  src/lib-components/SectionWrapper.vue
Labels: fix

#412 chore: update to latest design tokens
  package-lock.json
  package.json
Labels: chore

#413 fix: change ucla library website to site search
  src/lib-components/SearchHome.vue
Labels: fix

#414 feat: APPS-2458 Add Block- Amenities, Generic List, StaffSubjectLibrarian
  .gitignore
  serve/index.html
  serve/serve.css
  serve/serve.js
  serve/serve.vue
  src/App.vue
  src/lib-components/BlockAmenities.vue
  src/lib-components/BlockCallToAction.vue
  src/lib-components/BlockCardWithIllustration.vue
  src/lib-components/BlockEvent.vue
  src/lib-components/BlockGenericList.vue
  src/lib-components/BlockSimpleCard.vue
  src/lib-components/BlockSpaces.vue
  src/lib-components/BlockSponsor.vue
  src/lib-components/BlockStaffSubjectLibrarian.vue
  src/lib-components/Flexible/MediaGallery/NewLightbox.vue
  src/lib-components/FooterPrimary.vue
  src/lib-components/FooterSock.vue
  src/lib-components/IconWithLink.vue
  src/lib-components/NavBreadcrumb.vue
  src/lib-components/SectionStaffOrcidPublications.vue
  src/lib-components/index.js
  src/stories/BlockAmenities.spec.js
  src/stories/BlockAmenities.stories.js
  src/stories/BlockGenericList.spec.js
  src/stories/BlockGenericList.stories.js
  src/stories/BlockStaffSubjectLibrarian.spec.js
  src/stories/BlockStaffSubjectLibrarian.stories.js
  src/types/types.ts
Labels: feature

#415 feat: APPS-2460 add header components
  .gitignore
  package.json
  src/App.vue
  src/lib-components/BlockAmenities.vue
  src/lib-components/BlockGenericList.vue
  src/lib-components/BlockStaffSubjectLibrarian.vue
  src/lib-components/ButtonLink.vue
  src/lib-components/ExampleMeapNavMastHead.vue
  src/lib-components/Flexible/MediaGallery/NewLightbox.vue
  src/lib-components/FooterSponsor.vue
  src/lib-components/HeaderMain.vue
  src/lib-components/HeaderMainResponsive.vue
  src/lib-components/HeaderSmart.vue
  src/lib-components/NavMenuItem.vue
  src/lib-components/NavMenuItemResponsive.vue
  src/lib-components/NavMenuItemScriptSetup.vue
  src/lib-components/NavPrimary.vue
  src/lib-components/NavSecondary.vue
  src/lib-components/SearchResult.vue
  src/lib-components/SingleCheckbox.vue
  src/lib-components/index.js
  src/stories/BlockGenericList.stories.js
  src/stories/BlockStaffSubjectLibrarian.stories.js
  src/stories/ButtonLink.stories.js
  src/stories/ExampleMeapNavMastHead.stories.js
  src/stories/HeaderMainResponsive.spec.js
  src/stories/HeaderMainResponsive.stories.js
  src/stories/HeaderSmart.spec.js
  src/stories/HeaderSmart.stories.js
  src/stories/NavPrimary.spec.js
  src/stories/NavPrimary.stories.js
  src/stories/NavSecondary.spec.js
  src/stories/NavSecondary.stories.js
  src/types/types.ts
  vite.config.serve.ts
Labels: feature
