Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2023-02, with the labels that each got.

#321 feat: add registration type logic
  src/lib-components/BlockForm.vue
  src/stories/BannerFeatured.stories.js
  src/stories/BannerHeader.stories.js
  src/stories/BannerText.stories.js
  src/stories/BlockForm.stories.js
Labels: feature

#323 fix: add null check
  src/lib-components/Flexible/BannerFeatured.vue
  src/lib-components/Flexible/CardWithImage.vue
  src/lib-components/Flexible/Highlight.vue
  src/mixins/accessibleExternalLinks.js
Labels: fix

#322 feat: use rich-text in site alert and spaces, increase alert display time
  src/lib-components/BlockSpaces.vue
  src/lib-components/SiteNotificationAlert.vue
  src/stories/BlockSpaces.stories.js
  src/stories/SiteNotificationAlert.stories.js
  src/stories/mock-api.json
Labels: feature

#324 feat: add subscription code for mailing list in footer
  src/lib-components/FooterPrimary.vue
Labels: feature

#325 feat: updates BlockStaffDetail styling
  src/lib-components/BlockStaffDetail.vue
  src/stories/BlockStaffDetail.stories.js
Labels: feature

#327 fix: ThumbnailCard link, and credit if no caption
  src/lib-components/Flexible/MediaGallery.vue
  src/lib-components/Flexible/MediaGallery/ThumbnailCard.vue
  src/stories/Flexible_MediaGallery.spec.js
  src/stories/mock/Media.js
Labels: fix

#326 fix: update placeholder image height
  src/lib-components/BlockHighlight.vue
  src/stories/SectionTeaserCard.stories.js
  src/stories/SectionTeaserHighlight.stories.js
  src/stories/SectionTeaserList.stories.js
Labels: fix

#328 feat: add search-margin styling to divider
  src/lib-components/DividerWayFinder.vue
Labels: feature

#329 fix: SimpleCard truncaton
  src/lib-components/BlockSimpleCard.vue
  src/stories/BlockSimpleCard.stories.js
Labels: fix

#331 fix: raw json in staff detail > department field
  src/lib-components/BlockStaffDetail.vue
  src/stories/BlockStaffDetail.spec.js
  src/stories/BlockStaffDetail.stories.js
Labels: bugfix

#332 feat: APPS-2142 Update Search components placeholders
  src/lib-components/SearchGeneric.vue
  src/lib-components/SearchHome.vue
  src/stories/SearchGeneric.stories.js
Labels: feature

#330 fix: allow locations with no links
  src/lib-components/BannerFeatured.vue
  src/lib-components/BannerHeader.vue
  src/lib-components/BannerText.vue
  src/lib-components/BlockHighlight.vue
Labels: fix

#334 fix: APPS-2165 Update Contact a Subject Librarian section to include caption in table
  src/lib-components/SectionStaffSubjectLibrarian.vue
Labels: fix

#333 fix: APPS-2100_update-browse-by-default-state
  src/lib-components/AlphabeticalBrowseBy.vue
Labels: fix

#335 fix: external link styling
  src/lib-components/RichText.vue
Labels: fix

#336 fix: external link styling
  src/lib-components/RichText.vue
Labels: fix

#337 fix: block staff list clickable area and clickable links; block location list responsiveness
  src/lib-components/BlockLocationListItem.vue
  src/lib-components/BlockStaffList.vue
Labels: fix

#338 fix: height of block highlight used in section teaser list
  src/lib-components/BlockHighlight.vue
Labels: fix

#339 fix: APPS-2161 Update maxlength for block-staff-article-list on Program index
  src/lib-components/BlockStaffArticleList.vue
  src/stories/BlockStaffArticleList.stories.js
Labels: fix

#342 fix: fix blockhours url
  src/lib-components/BlockHours.vue
Labels: bugfix

#340 fix: BlockHighlight responsive title max-width
  src/lib-components/BlockHighlight.vue
  src/stories/BlockHighlight.stories.js
Labels: fix

#341 fix: Add audio and vidoe embed code to flexible media with text stories mock data.
  src/stories/mock/Flexible_MediaWithText.js
Labels: bugfix, chore
