Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2023-08, with the labels that each got.

#367 fix: button in banner-header component
  src/lib-components/BannerHeader.vue
Labels: fix

#368 fix: add keyup event handler to search home
  src/lib-components/SearchHome.vue
Labels: bugfix

#369 fix: change section summary to richtext in section wrapper
  src/lib-components/SectionWrapper.vue
Labels: fix

#366 feat: APPS-2381 add divider components
  ucla-library-website-components-vue3.x/.prettierrc.cjs
  ucla-library-website-components-vue3.x/.storybook/main.ts
  ucla-library-website-components-vue3.x/.storybook/preview.ts
  ucla-library-website-components-vue3.x/cypress.config.ts
  ucla-library-website-components-vue3.x/cypress/e2e/1-getting-started/todo.cy.js
  ucla-library-website-components-vue3.x/cypress/e2e/2-advanced-examples/actions.cy.js
  ucla-library-website-components-vue3.x/cypress/e2e/2-advanced-examples/aliasing.cy.js
  ucla-library-website-components-vue3.x/cypress/e2e/2-advanced-examples/assertions.cy.js
  ucla-library-website-components-vue3.x/cypress/e2e/2-advanced-examples/connectors.cy.js
  ucla-library-website-components-vue3.x/cypress/e2e/2-advanced-examples/cookies.cy.js
  ucla-library-website-components-vue3.x/cypress/e2e/2-advanced-examples/cypress_api.cy.js
  ucla-library-website-components-vue3.x/cypress/e2e/2-advanced-examples/files.cy.js
  ucla-library-website-components-vue3.x/cypress/e2e/2-advanced-examples/location.cy.js
  ucla-library-website-components-vue3.x/cypress/e2e/2-advanced-examples/misc.cy.js
  ucla-library-website-components-vue3.x/cypress/e2e/2-advanced-examples/navigation.cy.js
  ucla-library-website-components-vue3.x/cypress/e2e/2-advanced-examples/network_requests.cy.js
  ucla-library-website-components-vue3.x/cypress/e2e/2-advanced-examples/querying.cy.js
  ucla-library-website-components-vue3.x/cypress/e2e/2-advanced-examples/spies_stubs_clocks.cy.js
  ucla-library-website-components-vue3.x/cypress/e2e/2-advanced-examples/storage.cy.js
  ucla-library-website-components-vue3.x/cypress/e2e/2-advanced-examples/traversal.cy.js
  ucla-library-website-components-vue3.x/cypress/e2e/2-advanced-examples/utilities.cy.js
  ucla-library-website-components-vue3.x/cypress/e2e/2-advanced-examples/viewport.cy.js
  ucla-library-website-components-vue3.x/cypress/e2e/2-advanced-examples/waiting.cy.js
  ucla-library-website-components-vue3.x/cypress/e2e/2-advanced-examples/window.cy.js
  ucla-library-website-components-vue3.x/cypress/fixtures/example.json
  ucla-library-website-components-vue3.x/cypress/support/commands.ts
  ucla-library-website-components-vue3.x/cypress/support/e2e.ts
  ucla-library-website-components-vue3.x/package-lock.json
  ucla-library-website-components-vue3.x/package.json
  ucla-library-website-components-vue3.x/src/App.vue
  ucla-library-website-components-vue3.x/src/components/DividerGeneral.vue
  ucla-library-website-components-vue3.x/src/components/DividerWayFinder.vue
  ucla-library-website-components-vue3.x/src/main.ts
  ucla-library-website-components-vue3.x/src/router.js
  ucla-library-website-components-vue3.x/src/stories/DividerGeneral.spec.js
  ucla-library-website-components-vue3.x/src/stories/DividerGeneral.stories.js
  ucla-library-website-components-vue3.x/src/stories/Header.stories.ts
  ucla-library-website-components-vue3.x/src/stories/Page.stories.ts
  ucla-library-website-components-vue3.x/src/styles/global.scss
  ucla-library-website-components-vue3.x/src/utils/getSectionName.js
  ucla-library-website-components-vue3.x/tsconfig.json
  ucla-library-website-components-vue3.x/vite.config.ts
Labels: feature

#372 fix: APPS-2367 Lighten shadow overlay
  src/lib-components/BannerHeader.vue
Labels: fix

#370 fix: update - change section summary to richtext in section wrapper
  src/lib-components/SectionWrapper.vue
  src/stories/SectionWrapper.spec.js
  src/stories/SectionWrapper.stories.js
Labels: fix

#374 chore: Add dev server to use component library as a plugin
  dev/index.html
  dev/serve.js
  dev/serve.vue
  package.json
  vite.config.serve.ts
Labels: chore

#375 fix: APPS-2392 update design token
  package-lock.json
  package.json
Labels: fix

#376 chore: nuxt recommends pnpm
  .npmrc
  package-lock.json
  package.json
  pnpm-lock.yaml
  vite.config.ts
Labels: chore

#377 ci: APPS-2409 npm next release
  .github/workflows/publish-to-npm.yml
  package.json
  release.config.js
Labels: ci

#378 ci: APPS-2409 remove type=module from package.json and add server port for serve which dev server for component library entry file
  package.json
  vite.config.serve.ts
Labels: ci

#379 chore: fix package.json name
  package.json
Labels: chore

#380 fix: if package.json changes run pnpm install
  pnpm-lock.yaml
Labels: bugfix

#381 fix: build a new version for next release candidate
  README.md
Labels: bugfix

#382 ci: update github workflows to use pnpm and new percy and netlify projects
  .eslintrc.cjs
  .github/workflows/ci.yml
  .github/workflows/percy.yml
  .github/workflows/publish-to-npm.yml
  .github/workflows/setup-workspace/action.yml
  .gitignore
  cypress.config.ts
  cypress/e2e/1-getting-started/todo.cy.js
  cypress/e2e/2-advanced-examples/actions.cy.js
  cypress/e2e/2-advanced-examples/aliasing.cy.js
  cypress/e2e/2-advanced-examples/assertions.cy.js
  cypress/e2e/2-advanced-examples/connectors.cy.js
  cypress/e2e/2-advanced-examples/cookies.cy.js
  cypress/e2e/2-advanced-examples/cypress_api.cy.js
  cypress/e2e/2-advanced-examples/files.cy.js
  cypress/e2e/2-advanced-examples/location.cy.js
  cypress/e2e/2-advanced-examples/misc.cy.js
  cypress/e2e/2-advanced-examples/navigation.cy.js
  cypress/e2e/2-advanced-examples/network_requests.cy.js
  cypress/e2e/2-advanced-examples/querying.cy.js
  cypress/e2e/2-advanced-examples/spies_stubs_clocks.cy.js
  cypress/e2e/2-advanced-examples/storage.cy.js
  cypress/e2e/2-advanced-examples/traversal.cy.js
  cypress/e2e/2-advanced-examples/utilities.cy.js
  cypress/e2e/2-advanced-examples/viewport.cy.js
  cypress/e2e/2-advanced-examples/waiting.cy.js
  cypress/e2e/2-advanced-examples/window.cy.js
  cypress/support/commands.js
  cypress/support/e2e.js
  dev/serve.vue
  package.json
  pnpm-lock.yaml
  src/App.vue
  src/components/DividerGeneral.vue
  src/components/DividerWayFinder.vue
  src/components/HelloWorld.vue
  src/stories/Button.stories.ts
  src/stories/Button.vue
  src/stories/Header.stories.ts
  src/stories/Header.vue
  src/stories/Page.stories.ts
  src/stories/Page.vue
  src/stories/mocks/vue-router.mock.js
  tsconfig.json
  tsconfig.vite-config.json
Labels: ci

#383 fix: ci workflows, test npm release
  .github/workflows/ci.yml
  .github/workflows/percy.yml
Labels: bugfix
