Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2023-07, with the labels that each got.

#350 fix: add "Y" to alphabetical browseby component
  src/lib-components/AlphabeticalBrowseBy.vue
Labels: fix

#351 fix: replace chaining operator that is not supported in nuxt2 yet it is es2020 syntax
  src/lib-components/SearchInput.vue
Labels: bugfix

#352 fix: remove search-input scoped slots not supported by nuxt2
  src/lib-components/SearchInput.vue
Labels: bugfix

#353 fix: replace v-if with v-show for hydration issues in nuxt2
  src/lib-components/SearchInput.vue
Labels: bugfix

#354 fix: add support for enter key for searching
  src/lib-components/SearchGeneric.vue
Labels: bugfix

#347 feat: APPS-2292 Create PageAnchor component
  dev/serve.vue
  src/lib-components/Flexible/GridGalleryCards.vue
  src/lib-components/GridGallery.vue
  src/lib-components/PageAnchor.vue
  src/lib-components/SectionWrapper.vue
  src/lib-components/index.js
  src/mixins/kebabCase.js
  src/stories/PageAnchor.stories.js
  src/stories/PullQuote.stories.js
Labels: feature

#355 chore: add lint script and eslint packages for vue and cypress
  ucla-library-website-components-vue3.x/package-lock.json
  ucla-library-website-components-vue3.x/package.json
Labels: chore

#356 chore: add cypress
  ucla-library-website-components-vue3.x/package-lock.json
  ucla-library-website-components-vue3.x/package.json
Labels: chore

#359 chore: add vue to peer dependencies
  ucla-library-website-components-vue3.x/package.json
Labels: chore

#360 chore: add node and npm version to package.json
  ucla-library-website-components-vue3.x/package.json
Labels: chore

#361 chore: Add eslint
  ucla-library-website-components-vue3.x/.eslintrc.cjs
  ucla-library-website-components-vue3.x/package-lock.json
  ucla-library-website-components-vue3.x/package.json
  ucla-library-website-components-vue3.x/tsconfig.json
Labels: chore

#363 chore: Add prettier
  ucla-library-website-components-vue3.x/.prettierrc.cjs
  ucla-library-website-components-vue3.x/package-lock.json
  ucla-library-website-components-vue3.x/package.json
  ucla-library-website-components-vue3.x/src/App.vue
  ucla-library-website-components-vue3.x/src/components/HelloWorld.vue
  ucla-library-website-components-vue3.x/src/main.ts
Labels: chore

#365 chore: add storybook
  ucla-library-website-components-vue3.x/.eslintrc.cjs
  ucla-library-website-components-vue3.x/.storybook/main.ts
  ucla-library-website-components-vue3.x/.storybook/preview.ts
  ucla-library-website-components-vue3.x/package-lock.json
  ucla-library-website-components-vue3.x/package.json
  ucla-library-website-components-vue3.x/src/stories/Button.stories.ts
  ucla-library-website-components-vue3.x/src/stories/Button.vue
  ucla-library-website-components-vue3.x/src/stories/Configure.mdx
  ucla-library-website-components-vue3.x/src/stories/Header.stories.ts
  ucla-library-website-components-vue3.x/src/stories/Header.vue
  ucla-library-website-components-vue3.x/src/stories/Page.stories.ts
  ucla-library-website-components-vue3.x/src/stories/Page.vue
  ucla-library-website-components-vue3.x/src/stories/assets/accessibility.png
  ucla-library-website-components-vue3.x/src/stories/assets/accessibility.svg
  ucla-library-website-components-vue3.x/src/stories/assets/addon-library.png
  ucla-library-website-components-vue3.x/src/stories/assets/assets.png
  ucla-library-website-components-vue3.x/src/stories/assets/context.png
  ucla-library-website-components-vue3.x/src/stories/assets/discord.svg
  ucla-library-website-components-vue3.x/src/stories/assets/docs.png
  ucla-library-website-components-vue3.x/src/stories/assets/figma-plugin.png
  ucla-library-website-components-vue3.x/src/stories/assets/github.svg
  ucla-library-website-components-vue3.x/src/stories/assets/share.png
  ucla-library-website-components-vue3.x/src/stories/assets/styling.png
  ucla-library-website-components-vue3.x/src/stories/assets/testing.png
  ucla-library-website-components-vue3.x/src/stories/assets/theming.png
  ucla-library-website-components-vue3.x/src/stories/assets/tutorials.svg
  ucla-library-website-components-vue3.x/src/stories/assets/youtube.svg
  ucla-library-website-components-vue3.x/src/stories/button.css
  ucla-library-website-components-vue3.x/src/stories/header.css
  ucla-library-website-components-vue3.x/src/stories/page.css
Labels: chore
