Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2024-01, with the labels that each got.

#428 feat: APPS-2535 Add ResponsiveVideo to Banner components
  src/lib-components/BannerFeatured.vue
  src/lib-components/BannerHeader.vue
  src/lib-components/BlockCardWithImage.vue
  src/lib-components/BlockClippedDate.vue
  src/lib-components/BlockDate.vue
  src/lib-components/BlockFloatingHighlight.vue
  src/lib-components/ButtonLink.vue
  src/lib-components/Flexible/MediaGallery/NewLightbox.vue
  src/lib-components/MastheadSecondary.vue
  src/lib-components/Media/Item.vue
  src/lib-components/ResponsiveImage.vue
  src/lib-components/ResponsiveVideo.vue
  src/lib-components/SectionDualMasonry.vue
  src/stores/mock.js
  src/stories/BannerFeatured.stories.js
  src/stories/BannerHeader.stories.js
  src/stories/BlockSponsor.stories.js
  src/stories/MastheadSecondary.stories.js
  src/stories/ResponsiveImage.stories.js
  src/stories/ResponsiveVideo.stories.js
  src/types/types.ts
Labels: feature

#429 feat: APPS-2527 ImpactNumberCard component
  src/lib-components/ImpactNumberCard.vue
  src/lib-components/index.js
  src/stories/ImpactNumberCard.spec.js
  src/stories/ImpactNumberCard.stories.js
Labels: feature

#430 feat: APPS-2526 GridGallery component
  src/lib-components/GridGallery.vue
  src/lib-components/index.js
  src/stories/GridGallery.spec.js
  src/stories/GridGallery.stories.js
  src/types/types.ts
Labels: feature

#431 feat: APPS-2528 FlexibleGridGalleryCards component
  src/lib-components/BannerHeader.vue
  src/lib-components/Flexible/GridGalleryCards.vue
  src/lib-components/index.js
  src/stories/Flexible_GridGalleryCards.spec.js
  src/stories/Flexible_GridGalleryCards.stories.js
  src/types/flexible_gridgallery.ts
  src/types/types.ts
  src/utils/stripMeapFromURI.js
Labels: feature

#432 feat: APPS-2523 FlexibleCallToAction component
  src/lib-components/Flexible/CallToAction.vue
  src/lib-components/Flexible/GridGalleryCards.vue
  src/lib-components/index.js
  src/stories/Flexible_CallToAction.spec.js
  src/stories/Flexible_CallToAction.stories.js
  src/types/flexible_types.ts
Labels: feature

#434 fix: ci npm publish add node version setup for node version 20
  .github/workflows/publish-to-npm.yml
Labels: bugfix

#435 fix: update search when clearing search bar
  src/lib-components/SearchGeneric.vue
  src/lib-components/SearchInput.vue
Labels: bugfix, fix

#433 feat: APPS-2524 FlexibleCallToActionTwoUp component
  src/lib-components/BlockCallToActionTwoUp.vue
  src/lib-components/Flexible/CallToAction.vue
  src/lib-components/Flexible/CallToActionTwoUp.vue
  src/lib-components/Flexible/GridGalleryCards.vue
  src/lib-components/index.js
  src/stories/Flexible_CallToActionTwoUp.spec.js
  src/stories/Flexible_CallToActionTwoUp.stories.js
  src/types/flexible_types.ts
  src/types/types.ts
Labels: feature

#437 feat: APPS-2516 Add block remove search filter to vue3 branch
  .gitignore
  README.md
  src/lib-components/BlockRemoveSearchFilter.vue
  src/lib-components/index.js
  src/stories/BlockRemoveSearchFilter.spec.js
  src/stories/BlockRemoveSearchFilter.stories.js
Labels: feature

#438 feat: APPS-2521 Add FlexibleAssociatedTopicCards component
  src/lib-components/Flexible/AssociatedTopicCards.vue
  src/lib-components/index.js
  src/stories/Flexible_AssociatedTopicCards.spec.js
  src/stories/Flexible_AssociatedTopicCards.stories.js
  src/types/flexible_types.ts
Labels: feature
