Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2024-11, with the labels that each got.

#649 fix: update category for impact report story to impact report spotlight
  .github/workflows/setup-workspace/action.yml
  package.json
  pnpm-lock.yaml
  src/lib-components/Flexible/BannerFeatured.vue
Labels: enhancement, feature

#650 feat: fix pnpm version in publish action
  .github/workflows/publish-to-npm.yml
Labels: bugfix

#651 fix: replace impact report spotlight with just one word spotlight
  src/lib-components/Flexible/BannerFeatured.vue
Labels: bugfix

#647 feat: APPS-1974_Add numbered page buttons to SectionPagination
  src/lib-components/SectionPagination.vue
  src/stories/SectionPagination.stories.js
  src/styles/default/_section-pagination.scss
  src/styles/ftva/_section-pagination.scss
Labels: feature

#658 fix: APPS-3074 add watchers for pagination reactivity
  src/lib-components/SectionPagination.vue
  src/stories/SectionPagination.stories.js
Labels: fix

#653 feat: APPS-3058 Create FTVA variation of SectionStaffArticleList
  src/lib-components/BlockStaffArticleList.vue
  src/lib-components/SectionStaffArticleList.vue
  src/stories/BlockStaffArticleList.stories.js
  src/stories/SectionStaffArticleList.stories.js
  src/styles/_base.scss
  src/styles/_ftva-theme.scss
  src/styles/default/_block-staff-article-item.scss
  src/styles/default/_section-staff-article-list.scss
  src/styles/ftva/_block-staff-article-item.scss
  src/styles/ftva/_section-staff-article-list.scss
  src/types/types.ts
  src/utils/formatEventSeriesDates.js
Labels: feature

#655 feat: APPS-3049 Create Calendar component (Part 1)
  .github/workflows/ci.yml
  .github/workflows/setup-workspace/action.yml
  .storybook/VuetifyStoryWrapper.vue
  .storybook/preview.ts
  .storybook/withVuetifyTheme.decorator.js
  package.json
  pnpm-lock.yaml
  src/lib-components/BaseCalendar.vue
  src/lib-components/Flexible/MediaGallery.vue
  src/lib-components/index.js
  src/main.ts
  src/plugins/vuetify.ts
  src/stories/BaseCalendar.spec.js
  src/stories/BaseCalendar.stories.js
  src/stories/mock/CalendarEvents.js
  src/styles/default/_base-calendar.scss
  src/styles/ftva/_base-calendar.scss
  vite.config.ts
Labels: feature
