Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2024-10, with the labels that each got.

#625 feat: APPS-2954 MultiComponent update with DateCreated prop
  src/lib-components/BlockCardWithImage.vue
  src/lib-components/CardMeta.vue
  src/lib-components/SectionTeaserCard.vue
  src/stories/BlockCardWithImage.stories.js
  src/stories/SectionTeaserCard.stories.js
  src/styles/ftva/_block-card-with-image.scss
  src/types/types.ts
Labels: enhancement

#628 chore: APPS-2992 move min height styles to sectionTeaserCard
  src/styles/ftva/_section-teaser-card.scss
Labels: chore

#627 feat: APPS-2963 Update FlexibleBlocks component with FTVA theme
  src/lib-components/FlexibleBlocks.vue
  src/stories/FlexibleBlocks.stories.js
  src/stories/TwoColLayoutWStickySideBar.stories.js
  src/stories/mock/SocialList.js
  src/styles/ftva/_section-wrapper.scss
Labels: feature

#626 feat: APPS-2959 FlexibleMediaGallery FTVA variant
  src/lib-components/Flexible/MediaGallery.vue
  src/lib-components/Flexible/MediaGallery/BannerImage.vue
  src/lib-components/Flexible/MediaGallery/NewLightbox.vue
  src/lib-components/Flexible/MediaGallery/ThumbnailCard.vue
  src/lib-components/MediaBadge.vue
  src/stories/Flexible_MediaGallery.stories.js
  src/stories/MediaBadge.stories.js
  src/stories/MediaGallery_BannerImage.stories.js
  src/stories/MediaGallery_NewLightbox.stories.js
  src/stories/MediaGallery_ThumbnailCard.stories.js
  src/stories/mock/FTVAMedia.js
  src/styles/default/_media-badge.scss
  src/styles/default/_media-gallery-banner-image.scss
  src/styles/default/_media-gallery-thumbnail-card.scss
  src/styles/default/_media-gallery.scss
  src/styles/ftva/_media-badge.scss
  src/styles/ftva/_media-gallery-banner-image.scss
  src/styles/ftva/_media-gallery-thumbnail-card.scss
  src/styles/ftva/_media-gallery.scss
  src/styles/ftva/_new-lightbox.scss
Labels: enhancement

#629 chore: APPS-3000 Update global store with FTVA viewing info
  src/stores/GlobalStore.js
Labels: chore

#632 fix: add relative position to anchor link on card
  src/lib-components/BlockCardThreeColumn.vue
Labels: fix

#630 feat: APPS-2999 Add BlockCTA FTVA variants
  package.json
  pnpm-lock.yaml
  src/lib-components/BlockCallToAction.vue
  src/lib-components/TwoColLayoutWStickySideBar.vue
  src/stories/BlockCallToAction.stories.js
  src/stories/TwoColLayoutWStickySideBar.stories.js
  src/styles/default/_block-call-to-action.scss
  src/styles/ftva/_block-call-to-action.scss
Labels: enhancement

#631 fix: APPS-2984 Share/Calendar button dropdown behavior
  src/lib-components/ButtonDropdown.vue
  src/styles/default/_button-dropdown.scss
  src/styles/ftva/_button-dropdown.scss
Labels: fix

#635 fix: APPS-3004 Fix Location links in component BlockEventDetail
  src/lib-components/BlockEventDetail.vue
  src/stories/BlockEventDetail.stories.js
Labels: fix

#636 fix: APPS-2983 Add fixed-width value to sidebar column
  src/lib-components/TwoColLayoutWStickySideBar.vue
Labels: enhancement

#633 fix: APPS-2969 Add hover state to FTVA card-horizontal titles
  src/lib-components/BlockCardThreeColumn.vue
  src/styles/ftva/_block-card-with-image.scss
  src/styles/ftva/_rich-text.scss
Labels: fix

#637 fix: Apps-2922 remove time stamp on homepage
  src/lib-components/CardMeta.vue
  src/lib-components/SectionTeaserCard.vue
  src/stories/SectionWrapper.stories.js
Labels: fix

#634 fix: APPS-3007 Use RichText comp in BlockCTA comp
  src/lib-components/BlockCallToAction.vue
  src/styles/default/_block-call-to-action.scss
  src/styles/ftva/_block-call-to-action.scss
Labels: fix

#638 fix: APPS-2972 Reformat dates to exclude the leading zero on single digit dates
  src/lib-components/BlockCardThreeColumn.vue
  src/stories/BlockCardThreeColumn.stories.js
  src/stories/BlockClippedDate.stories.js
  src/stories/SectionTeaserList.stories.js
Labels: fix

#642 feat: APPS 2793 Add selected state to FTVA filters
  src/lib-components/BlockRemoveSearchFilter.vue
  src/stories/BlockRemoveSearchFilter.stories.js
  src/styles/ftva/_block-remove-search-filter.scss
Labels: enhancement

#641 feat: APPS-2989 upgrade vue3 version and its dependencies to the latest versions
  .github/workflows/setup-workspace/action.yml
  .storybook/main.ts
  package.json
  pnpm-lock.yaml
  src/lib-components/BlockStaffDetail.vue
  src/lib-components/BlockStaffList.vue
  src/lib-components/BlockStaffSubjectLibrarian.vue
  tsconfig.json
  tsconfig.vite-config.json
Labels: feature, refactor

#639 fix: APPS-2976 & APPS-3011 Updates to cardMeta - category & aboutAuthor
  src/lib-components/CardMeta.vue
  src/stories/CardMeta.stories.js
  src/styles/ftva/_card-meta.scss
Labels: fix

#643 fix: APPS-2889 styles for screening text
  src/styles/ftva/_block-screening-detail.scss
Labels: fix

#644 fix: APPS-3030 Adjust TwoColumn component spacing
  src/lib-components/TwoColLayoutWStickySideBar.vue
Labels: fix

#646 fix: APPS-3041 Reset TwoCol component primary column width
  src/lib-components/TwoColLayoutWStickySideBar.vue
Labels: fix

#645 fix: APPS-3040 bold is not working in FTVA RichText
  package.json
  pnpm-lock.yaml
  src/stories/mock/RichText.js
  src/styles/ftva/_rich-text.scss
Labels: fix

#648 fix: APPS-3046 Remove excess content spacing in SlimBlockCTA
  src/styles/default/_block-call-to-action.scss
Labels: fix
