Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2024-12, with the labels that each got.

#659 feat: Apps-3068 SEO friendly SectionPagination
  src/lib-components/SectionPagination.vue
  src/stories/SectionPagination.stories.js
Labels: feature

#663 fix: APPS-3090 Move CSS from EventSeries page to SectionStaffArticleList component for FTVA Theme
  src/lib-components/SectionStaffArticleList.vue
  src/stories/SectionStaffArticleList.stories.js
  src/stories/SectionWrapper.stories.js
  src/styles/ftva/_section-staff-article-list.scss
  src/styles/ftva/_section-wrapper.scss
Labels: fix

#661 feat: APPS 3079 Calendar Component EventCard Popup
  pnpm-lock.yaml
  src/lib-components/BaseCalendar.vue
  src/lib-components/CardMeta.vue
  src/plugins/vuetify.ts
  src/stories/BaseCalendar.stories.js
  src/stories/mock/CalendarEvents.js
  src/styles/default/_base-calendar.scss
  src/styles/ftva/_base-calendar.scss
Labels: feature

#666 feat: APPS-3100 Decouple SectionRemoveSearchFilter
  src/lib-components/BlockRemoveSearchFilter.vue
  src/lib-components/DateFilter.vue
  src/lib-components/SearchGenericFilters.vue
  src/lib-components/SectionRemoveSearchFilter.vue
  src/stories/SectionRemoveSearchFilter.stories.js
Labels: enhancement, feature

#664 feat: Apps-3035 create filters drop down component
  package.json
  pnpm-lock.yaml
  src/lib-components/FiltersDropdown.vue
  src/lib-components/MobileDrawer.vue
  src/stories/FiltersDropdown.spec.js
  src/stories/FiltersDropdown.stories.js
  src/styles/default/_filters-dropdown.scss
  src/styles/ftva/_filters-dropdown.scss
Labels: feature

#665 chore: add a test for datefilter emit behavior
  src/stories/DateFilter.spec.js
  src/stories/DateFilter.stories.js
Labels: chore

#662 feat: APPS-3078 add is highlighted to blockcardthreecolumn
  src/lib-components/BlockCardThreeColumn.vue
  src/stories/BlockCardThreeColumn.stories.js
  src/types/types.ts
Labels: feature

#667 fix: APPS 3080 Update TabList buttons with SEO logic
  pnpm-lock.yaml
  src/lib-components/TabList.vue
  src/stories/TabToggle.stories.js
Labels: enhancement

#668 fix: export filtersdropdown because I forgot!
  src/lib-components/index.js
Labels: chore, fix

#669 chore: APPS-3112 unify styles between datefilter and filterdropdown
  src/lib-components/DateFilter.vue
  src/lib-components/FiltersDropdown.vue
  src/styles/default/_filters-dropdown.scss
  src/styles/default/_mobile-drawer.scss
  src/styles/ftva/_filters-dropdown.scss
Labels: chore

#670 fix: update readme with pr labels to use, and reset page number
  README.md
  src/lib-components/TabList.vue
Labels: chore

#671 fix: APPS-3117 Additional Component Fixes for EventListing Page
  src/lib-components/BaseCalendar.vue
  src/lib-components/BlockCardThreeColumn.vue
  src/styles/default/_base-calendar.scss
Labels: fix
