Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2024-04, with the labels that each got.

#478 feat: APPS-2619
  package.json
  pnpm-lock.yaml
  src/lib-components/BaseCheckboxGroup.vue
  src/lib-components/BaseRadioGroup.vue
  src/lib-components/SearchGenericFilterButtons.vue
  src/lib-components/SearchGenericFilters.vue
  src/lib-components/SearchGenericViewModes.vue
  src/lib-components/SectionRemoveSearchFilter.vue
  src/lib-components/SingleCheckbox.vue
  src/lib-components/index.js
  src/stories/BaseCheckboxGroup.stories.js
  src/stories/BaseRadioGroup.stories.js
  src/stories/SearchGenericFilterButtons.stories.js
  src/stories/SearchGenericFilters.stories.js
  src/stories/SearchGenericViewModes.stories.js
  src/stories/SectionRemoveSearchFilter.stories.js
  src/stories/SingleCheckbox.stories.js
Labels: feature

#482 feat: APPS-2570, APPS-2557 convert BlockLocationListItem and SectionLocationList
  src/lib-components/BlockLocationListItem.vue
  src/lib-components/SectionLocationList.vue
  src/lib-components/index.js
  src/stories/BlockLocationListItem.spec.js
  src/stories/BlockLocationListItem.stories.js
  src/stories/SectionLocationList.spec.js
  src/stories/SectionLocationList.stories.js
  src/types/types.ts
Labels: feature

#484 fix: typehandle error
  src/lib-components/Flexible/CardWithImage.vue
  src/stories/FlexibleBlocks.stories.js
Labels: bugfix

#486 fix: pay rate should display in block generic list
  src/lib-components/BlockGenericList.vue
Labels: bugfix

#485 feat: APPS-2556 Convert BlockHours to vue3
  src/lib-components/BlockHours.vue
  src/lib-components/index.js
  src/stories/BlockHours.spec.js
  src/stories/BlockHours.stories.js
Labels: feature

#487 feat: APPS-2569 convert SectionGenericList to vue3
  src/lib-components/SectionGenericList.vue
  src/lib-components/index.js
  src/stories/SectionGenericList.spec.js
  src/stories/SectionGenericList.stories.js
  src/types/types.ts
Labels: feature

#489 fix: section wrapper for prerender
  src/lib-components/BlockCardWithIllustration.vue
  src/lib-components/BlockHours.vue
  src/lib-components/BlockLocationListItem.vue
  src/lib-components/BlockMediaWithText.vue
  src/lib-components/SectionWrapper.vue
Labels: bugfix

#488 feat: APPS-2555 convert PageAnchor to vue 3
  src/lib-components/PageAnchor.vue
  src/lib-components/index.js
  src/stories/PageAnchor.spec.js
  src/stories/PageAnchor.stories.js
Labels: feature

#490 feat: APPS-2633_APPS-2636 Convert BlockStaffList & SectionStaffList to vue3
  src/lib-components/BlockStaffList.vue
  src/lib-components/SectionStaffList.vue
  src/lib-components/index.js
  src/stories/BlockStaffList.spec.js
  src/stories/BlockStaffList.stories.js
  src/stories/SectionStaffList.spec.js
  src/stories/SectionStaffList.stories.js
  src/types/types.ts
Labels: feature

#491 feat: APPS-2634_APPS-2581 Convert BlockStaffArticleList & SectionStaffArticleList
  src/lib-components/BlockStaffArticleList.vue
  src/lib-components/SectionStaffArticleList.vue
  src/stories/BlockStaffArticleList.spec.js
  src/stories/BlockStaffArticleList.stories.js
  src/stories/SectionStaffArticleList.spec.js
  src/stories/SectionStaffArticleList.stories.js
Labels: feature

#493 feat: Apps-2559 convert HeaderSticky to vue3
  src/lib-components/HeaderSticky.vue
  src/lib-components/index.js
  src/stories/HeaderSticky.spec.js
  src/stories/HeaderSticky.stories.js
Labels: feature

#492 feat: provide inject can be refs
  src/lib-components/BlockForm.vue
  src/lib-components/ButtonLink.vue
  src/lib-components/SectionHeader.vue
  src/lib-components/SectionWrapper.vue
  src/stories/BlockForm.stories.js
  src/stories/mock/BlockFormData.json
Labels: bugfix

#494 feat: APPS-2583-2582 Fix block StaffSubjectLibrarian & Convert SectionStaffSubjectLibrarian to vue3
  src/lib-components/BlockStaffSubjectLibrarian.vue
  src/lib-components/SectionStaffSubjectLibrarian.vue
  src/lib-components/SectionWrapper.vue
  src/lib-components/index.js
  src/stories/BlockStaffSubjectLibrarian.stories.js
  src/stories/SectionStaffSubjectLibrarian.spec.js
  src/stories/SectionStaffSubjectLibrarian.stories.js
Labels: feature

#495 chore: Apps-2640 update BlockGenericList.vue with same fix as vue 2 version
  src/lib-components/BlockGenericList.vue
  src/stories/BlockGenericList.stories.js
Labels: chore

#497 feat: APPS-2635 Convert BlockStaffDetail to vue3
  src/lib-components/BlockGenericList.vue
  src/lib-components/BlockStaffDetail.vue
  src/lib-components/BlockStaffSubjectLibrarian.vue
  src/lib-components/index.js
  src/stories/BlockStaffDetail.spec.js
  src/stories/BlockStaffDetail.stories.js
Labels: feature

#499 fix: Refactor StaffList & Add checks for MediaGallery
  src/lib-components/BlockLocationListItem.vue
  src/lib-components/BlockStaffList.vue
  src/lib-components/Flexible/MediaGallery.vue
  src/lib-components/SectionStaffList.vue
  src/stories/BlockStaffList.stories.js
  src/stories/SectionStaffList.stories.js
  src/types/types.ts
Labels: fix

#501 feat: Add SearchGeneric component
  package.json
  pnpm-lock.yaml
  src/lib-components/SearchGeneric.vue
  src/lib-components/SearchGenericFilters.vue
  src/lib-components/SearchInput.vue
  src/lib-components/SectionHeader.vue
  src/lib-components/SectionRemoveSearchFilter.vue
  src/lib-components/SectionWrapper.vue
  src/lib-components/index.js
  src/stories/SearchGeneric.spec.js
  src/stories/SearchGeneric.stories.js
Labels: feature

#503 fix: add search to masthead
  package.json
  pnpm-lock.yaml
  src/lib-components/ExampleMeapNavMastHead.vue
  src/lib-components/SearchGeneric.vue
  src/stories/ExampleMeapNavMastHead.stories.js
Labels: bugfix

#498 feat: APPS-2632 convert block & section PostSmall to vue3
  src/lib-components/BlockPostSmall.vue
  src/lib-components/SectionPostSmall.vue
  src/lib-components/index.js
  src/stories/BlockPostSmall.spec.js
  src/stories/BlockPostSmall.stories.js
  src/stories/SectionPostSmall.spec.js
  src/stories/SectionPostSmall.stories.js
Labels: feature

#505 feat: APPS-2265, Add clickoutside feature to search-generic component
  src/lib-components/SearchGenericFilters.vue
Labels: feature

#504 fix: APPS-2637 Fix issues in FlexibleBlock's nested components
  src/lib-components/BlockCallToAction.vue
  src/lib-components/FlexibleBlocks.vue
  src/lib-components/PullQuote.vue
  src/stories/BlockCallToAction.stories.js
  src/stories/BlockCallToActionTwoUp.stories.js
  src/stories/FlexibleBlocks.stories.js
  src/stories/Flexible_CallToAction.stories.js
  src/stories/Flexible_CallToAction2Up.stories.js
Labels: fix

#506 fix: APPS-2648 Fix BannerFeatured error in FlexibleBlock component
  src/lib-components/Flexible/BannerFeatured.vue
  src/stories/FlexibleBlocks.stories.js
  src/stories/Flexible_BannerFeatured.stories.js
  src/stories/mock/Flexible_Banner.js
Labels: bugfix
