Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2024-05, with the labels that each got.

#507 fix: APPS-2668 SearchHome.vue query param should be q
  src/lib-components/SearchHome.vue
  src/stories/SearchHome.spec.js
Labels: bugfix

#508 fix: APPS-2675 fix BlockStaffDetail.vue image type
  src/lib-components/BlockStaffDetail.vue
  src/stories/BlockStaffDetail.stories.js
Labels: bugfix

#509 fix: APPS-2665 When user clicks the x on search keyword, the search is not triggered automatically
  src/lib-components/SearchInput.vue
Labels: bugfix

#510 fix: search generic checkbox state
  src/lib-components/SearchGenericFilters.vue
Labels: bugfix

#511 chore: APPS-2557 carryover improvements from nuxt2 branch
  src/stories/CardMeta.stories.js
Labels: chore

#513 fix: APPS-2671 BannerFeatured digital eyebrow / category is not appearing
  package.json
  pnpm-lock.yaml
  src/lib-components/BannerFeatured.vue
  src/lib-components/Flexible/BannerFeatured.vue
  src/stories/Flexible_BannerFeatured.stories.js
  src/types/flexible_types.ts
Labels: fix

#514 fix: Fix tab focus in-out of search input field
  src/lib-components/SearchInput.vue
Labels: fix
