Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2024-07, with the labels that each got.

#538 fix: add console.log to divider component to test issue on the website
  src/lib-components/DividerWayFinder.vue
  src/stories/FlexibleBlocks.stories.js
Labels: bugfix

#540 fix: remove vue-router from external
  src/lib-components/DividerWayFinder.vue
  vite.config.ts
Labels: bugfix

#541 fix: APPS-2794
  package.json
  pnpm-lock.yaml
  vite.config.ts
Labels: bugfix

#523 feat: APPS-2701 Create DividerWayfinder & DividerGeneral component FTVA variation
  src/lib-components/DividerGeneral.vue
  src/lib-components/DividerWayFinder.vue
  src/stories/DividerGeneral.stories.js
  src/stories/DividerWayFinder.stories.js
  src/styles/_base.scss
  src/styles/_ftva-theme.scss
  src/styles/default/_divider-way-finder.scss
  src/styles/ftva/_divider-way-finder.scss
Labels: feature

#542 feat: Revert vitebuild code added previously
  .eslintrc
  package.json
  pnpm-lock.yaml
  src/lib-components/DateFilter.vue
  src/lib-components/SearchGeneric.vue
  src/lib-components/SectionRemoveSearchFilter.vue
  vite.config.ts
Labels: bugfix, feature, refactor

#530 feat: APPS-2774 Create CardMeta component FTVA variation
  package.json
  pnpm-lock.yaml
  release.config.cjs
  src/lib-components/BlockTag.vue
  src/lib-components/CardMeta.vue
  src/stories/BlockCampusMap.spec.js
  src/stories/CardMeta.stories.js
  src/styles/_base.scss
  src/styles/_default-theme.scss
  src/styles/_ftva-theme.scss
  src/styles/default/_card-meta.scss
  src/styles/ftva/_card-meta.scss
  src/types/types.ts
Labels: feature

#543 feat: fix csbuild
  package.json
  vite.config.ts
Labels: bugfix, feature, refactor

#544 feat: adds watcheffect onmounted for useroute reactivity
  package.json
  src/lib-components/DividerWayFinder.vue
  vite.config.ts
Labels: bugfix, feature

#547 feat: move vue-router back to external and peer dependencies
  package.json
  vite.config.ts
Labels: feature

#549 refactor: APPS-2801 refactor components to use mixins
  package.json
  pnpm-lock.yaml
  src/lib-components/BlockEventDetail.vue
  src/lib-components/BlockInfo.vue
  src/lib-components/BlockTag.vue
  src/lib-components/ButtonLink.vue
  src/stories/BlockEventDetail.stories.js
  src/stories/BlockTag.stories.js
  src/styles/_base.scss
  src/styles/_ftva-theme.scss
  src/styles/default/_blockeventdetail.scss
  src/styles/default/_blocktag.scss
  src/styles/default/_card-meta.scss
  src/styles/default/_divider-way-finder.scss
  src/styles/ftva/_block-info.scss
  src/styles/ftva/_blockeventdetail.scss
  src/styles/ftva/_blockremovesearchfilter.scss
  src/styles/ftva/_blocktag.scss
  src/styles/ftva/_button-link.scss
  src/styles/ftva/_card-meta.scss
  src/styles/global.scss
Labels: refactor

#539 feat: APPS-2788 Create Component FTVA NavSearch
  package.json
  pnpm-lock.yaml
  src/lib-components/NavSearch.vue
  src/stories/NavSearch.spec.js
  src/stories/NavSearch.stories.js
  src/styles/_base.scss
  src/styles/_ftva-theme.scss
  src/styles/default/_button-link.scss
  src/styles/default/_nav-search.scss
  src/styles/ftva/_nav-search.scss
Labels: feature

#555 feat: Update workflows for merge to main
  .github/workflows/ci.yml
  .github/workflows/percy.yml
Labels: fix

#557 feat: Revert specific commits to undo recent changes
  .github/workflows/publish-to-npm.yml
  CHANGELOG.md
  package.json
  src/lib-components/BannerHeader.vue
  src/lib-components/BlockGenericList.vue
  src/lib-components/Flexible/Form.vue
  src/lib-components/Flexible/MediaGallery.vue
  src/lib-components/Flexible/MediaGallery/BannerImage.vue
  src/lib-components/FlexibleBlocks.vue
  src/lib-components/ImpactNumbersCarousel.vue
  src/lib-components/RichText.vue
  src/lib-components/SearchHome.vue
  src/lib-components/SearchInput.vue
  src/lib-components/SectionRemoveSearchFilter.vue
  src/stories/MediaGallery.spec.js
Labels: feature

#550 feat: APPS-2790 Create Component FTVA Carousel -> NewLightbox
  src/lib-components/Flexible/MediaGallery/NewLightbox.vue
  src/stories/MediaGallery_NewLightbox.stories.js
  src/styles/_base.scss
  src/styles/_ftva-theme.scss
  src/styles/default/_new-lightbox.scss
  src/styles/ftva/_new-lightbox.scss
  src/types/types.ts
Labels: feature

#560 feat!: Update version to 3.0.0 for vue3.x switch to main
  .github/workflows/ci.yml
  .github/workflows/percy.yml
  CHANGELOG.md
  package.json
  release.config.cjs
  src/lib-components/BannerHeader.vue
  src/lib-components/BlockGenericList.vue
  src/lib-components/Flexible/Form.vue
  src/lib-components/Flexible/MediaGallery.vue
  src/lib-components/Flexible/MediaGallery/BannerImage.vue
  src/lib-components/Flexible/MediaGallery/NewLightbox.vue
  src/lib-components/FlexibleBlocks.vue
  src/lib-components/ImpactNumbersCarousel.vue
  src/lib-components/RichText.vue
  src/lib-components/SearchHome.vue
  src/lib-components/SearchInput.vue
  src/lib-components/SectionRemoveSearchFilter.vue
  src/stories/MediaGallery.spec.js
  src/stories/MediaGallery_NewLightbox.stories.js
  src/styles/_base.scss
  src/styles/_ftva-theme.scss
  src/styles/default/_new-lightbox.scss
  src/styles/ftva/_new-lightbox.scss
  src/types/types.ts
Labels: feature, breaking

#562 fix: workflow dispatch indentation issue
  .github/workflows/percy.yml
Labels: bugfix, ci

#563 feat: Create Component FTVA VideoEmbed
  src/lib-components/ResponsiveVideo.vue
  src/lib-components/VideoEmbed.vue
  src/stories/ResponsiveVideo.stories.js
  src/stories/VideoEmbed.spec.js
  src/stories/VideoEmbed.stories.js
Labels: feature

#548 feat: APPS-2700 Create Component FTVA Breadcrumb Variant
  src/lib-components/NavBreadcrumb.vue
  src/stories/NavBreadcrumb.stories.js
  src/styles/_base.scss
  src/styles/_ftva-theme.scss
  src/styles/default/_block-event-detail.scss
  src/styles/default/_block-remove-search-filter.scss
  src/styles/default/_block-tag.scss
  src/styles/default/_nav-breadcrumb.scss
  src/styles/ftva/_block-event-detail.scss
  src/styles/ftva/_block-remove-search-filter.scss
  src/styles/ftva/_block-tag.scss
  src/styles/ftva/_nav-breadcrumb.scss
Labels: enhancement, feature

#568 feat: Add trailing slash for internal links for percy to not create new snapshots
  src/lib-components/SmartLink.vue
Labels: enhancement

#564 chore: Update the Setup directions in the README
  README.md
Labels: chore

#566 feat: create ftva themes for BlockCardWithImage, SectionCardWithImage, + bugfix
  src/lib-components/BlockCardWithImage.vue
  src/lib-components/CardMeta.vue
  src/lib-components/SectionTeaserCard.vue
  src/stories/BlockCardWithImage.spec.js
  src/stories/BlockCardWithImage.stories.js
  src/stories/SectionTeaserCard.stories.js
  src/styles/_base.scss
  src/styles/_ftva-theme.scss
  src/styles/default/_block-card-with-image.scss
  src/styles/default/_section-teaser-card.scss
  src/styles/ftva/_block-card-with-image.scss
  src/styles/ftva/_card-meta.scss
  src/styles/ftva/_section-teaser-card.scss
  src/utils/formatEventDates.js
Labels: feature

#565 feat: APPS-2799 Create Components FTVA BlockScreeningDetail & SectionScreeningDetails
  src/lib-components/BlockScreeningDetail.vue
  src/lib-components/RichText.vue
  src/lib-components/SectionScreeningDetails.vue
  src/lib-components/VideoEmbed.vue
  src/lib-components/index.js
  src/stories/BlockScreeningDetail.spec.js
  src/stories/BlockScreeningDetail.stories.js
  src/stories/SectionScreeningDetails.spec.js
  src/stories/SectionScreeningDetails.stories.js
  src/styles/_ftva-theme.scss
  src/styles/ftva/_block-screening-detail.scss
  src/styles/ftva/_card-meta.scss
  src/types/types.ts
Labels: feature

#571 feat: externalize pinia in lib build
  vite.config.ts
Labels: bugfix

#573 fix: APPS-2847 NavBreadcrumb URI encoding
  src/lib-components/NavBreadcrumb.vue
  src/lib-components/SectionTeaserCard.vue
  src/stories/NavBreadcrumb.stories.js
Labels: fix

#576 fix: APPS 2841 Fix screening details components
  src/lib-components/BlockScreeningDetail.vue
  src/stories/BlockScreeningDetail.stories.js
  src/stories/SectionScreeningDetails.stories.js
Labels: fix

#575 fix: APPS-2843 Component BlockInfo Styling updates
  package.json
  pnpm-lock.yaml
  src/styles/ftva/_block-info.scss
Labels: fix
