Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2024-02, with the labels that each got.

#439 feat: APPS-2525 Add FlexibleForm component
  src/lib-components/Flexible/Form.vue
  src/lib-components/index.js
  src/stories/Flexible_Form.spec.js
  src/stories/Flexible_Form.stories.js
  src/types/flexible_types.ts
Labels: feature

#443 fix: APPS-2493 Hyperlink styling needed in FPB Highlight summary field
  src/lib-components/BlockHighlight.vue
  src/stories/BlockHighlight.stories.js
  src/stories/mock/Flexible_Highlight.js
Labels: fix

#442 feat: APPS-2522 Add FlexibleBannerFeatured component
  src/lib-components/BannerFeatured.vue
  src/lib-components/Flexible/BannerFeatured.vue
  src/lib-components/index.js
  src/stories/Flexible_BannerFeatured.spec.js
  src/stories/Flexible_BannerFeatured.stories.js
  src/types/flexible_types.ts
  src/types/types.ts
  src/utils/getPrompt.js
Labels: feature

#444 feat: APPS-2551 Add SectionTeaserList component
  src/lib-components/BlockClippedDate.vue
  src/lib-components/SectionTeaserList.vue
  src/lib-components/index.js
  src/stories/SectionTeaserList.spec.js
  src/stories/SectionTeaserList.stories.js
  src/types/types.ts
Labels: feature

#445 feat: APPS-2417 Add SectionTeaserHighlight component
  src/lib-components/SectionTeaserHighlight.vue
  src/lib-components/index.js
  src/stories/SectionTeaserHighlight.spec.js
  src/stories/SectionTeaserHighlight.stories.js
  src/types/types.ts
Labels: feature

#440 feat: APPS-2419 Add SectionTeaserCard component to vue3
  src/lib-components/BlockCardWithImage.vue
  src/lib-components/SectionCardsWithIllustrations.vue
  src/lib-components/SectionTeaserCard.vue
  src/lib-components/index.js
  src/stories/SectionTeaserCard.spec.js
  src/stories/SectionTeaserCard.stories.js
  src/style.css
Labels: feature

#446 feat: APPS-2550 Add FlexibleHighlight component
  src/lib-components/BannerFeatured.vue
  src/lib-components/BannerText.vue
  src/lib-components/BlockCardWithImage.vue
  src/lib-components/BlockClippedDate.vue
  src/lib-components/BlockFloatingHighlight.vue
  src/lib-components/BlockGenericList.vue
  src/lib-components/CardMeta.vue
  src/lib-components/Flexible/Highlight.vue
  src/lib-components/SiteBrandBar.vue
  src/lib-components/SiteNotificationAlert.vue
  src/lib-components/SmartLink.vue
  src/lib-components/index.js
  src/stories/CardMeta.stories.js
  src/stories/Flexible_Highlight.spec.js
  src/stories/Flexible_Highlight.stories.js
  src/stories/mock/Flexible_Highlight.js
  src/types/flexible_types.ts
  src/types/types.ts
Labels: feature

#448 fix: APPS-2411 fix section name with color-default, since route path is undefined
  src/lib-components/BlockCardWithImage.vue
  src/lib-components/BlockClippedDate.vue
  src/lib-components/BlockFloatingHighlight.vue
  src/lib-components/DividerWayFinder.vue
  src/stories/SectionTeaserHighlight.stories.js
Labels: bugfix

#449 feat: APPS-2567 Add FlexibleGalleryBannerImage, MediaBadge
  src/lib-components/Flexible/MediaGallery/BannerImage.vue
  src/lib-components/MediaBadge.vue
  src/lib-components/index.js
  src/stories/MediaBadge.spec.js
  src/stories/MediaBadge.stories.js
  src/stories/MediaGallery_BannerImage.spec.js
  src/stories/MediaGallery_BannerImage.stories.js
Labels: feature

#447 feat: APPS-2568 Add FlexibleGalleryThumbnailCard
  src/lib-components/Flexible/MediaGallery/ThumbnailCard.vue
  src/lib-components/index.js
  src/stories/MediaGallery_ThumbnailCard.spec.js
  src/stories/MediaGallery_ThumbnailCard.stories.js
Labels: feature

#451 feat: APPS-2529 Add FlexibleImpactNumberCards component to vue3 branch
  src/lib-components/Flexible/ImpactNumberCards.vue
  src/lib-components/index.js
  src/stories/Flexible_ImpactNumberCards.spec.js
  src/stories/Flexible_ImpactNumberCards.stories.js
  src/types/flexible_types.ts
Labels: feature

#452 fix: Fix useroute
  .eslintrc
  src/lib-components/BlockClippedDate.vue
  src/lib-components/BlockFloatingHighlight.vue
  src/lib-components/BlockRemoveSearchFilter.vue
  src/lib-components/DividerWayFinder.vue
Labels: bugfix

#454 fix: remove duplicate color which was causing hydration error
  src/lib-components/BlockClippedDate.vue
  src/lib-components/BlockFloatingHighlight.vue
  src/lib-components/BlockRemoveSearchFilter.vue
  src/lib-components/DividerWayFinder.vue
Labels: bugfix

#455 fix: check if route exists in cardmeta and navprimary
  src/lib-components/CardMeta.vue
  src/lib-components/NavPrimary.vue
Labels: bugfix

#457 feat: APPS:2562 add Flexible/PullQuote component to vue3
  src/lib-components/Flexible/PullQuote.vue
  src/lib-components/PullQuote.vue
  src/lib-components/index.js
  src/stories/Flexible_PullQuote.spec.js
  src/stories/Flexible_PullQuote.stories.js
  src/stories/PullQuote.stories.js
  src/types/flexible_types.ts
Labels: feature

#462 chore: APPS-2474 accessibility fixes
  package.json
  pnpm-lock.yaml
  src/lib-components/SectionWrapper.vue
Labels: chore

#458 feat: APPS-2560 Add FlexibleMediaGallery + Vue3 Carousel
  package.json
  pnpm-lock.yaml
  src/lib-components/BlockClippedDate.vue
  src/lib-components/BlockFloatingHighlight.vue
  src/lib-components/Flexible/Highlight.vue
  src/lib-components/Flexible/MediaGallery.vue
  src/lib-components/Flexible/MediaGallery/BannerImage.vue
  src/lib-components/Flexible/MediaGallery/NewLightbox.vue
  src/lib-components/Flexible/MediaGallery/ThumbnailCard.vue
  src/lib-components/index.js
  src/stories/Flexible_MediaGallery.spec.js
  src/stories/Flexible_MediaGallery.stories.js
  src/stories/MediaGallery_NewLightbox.spec.js
  src/stories/MediaGallery_NewLightbox.stories.js
  src/types/flexible_types.ts
Labels: feature
