Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2024-06, with the labels that each got.

#515 feat: APPS-2738 convert script setup to options api
  src/lib-components/FooterSponsor.vue
Labels: bugfix, feature

#522 feat: APPS-2704 create tags component
  src/composables/useTheme.js
  src/lib-components/BlockRemoveSearchFilter.vue
  src/lib-components/BlockTag.vue
  src/lib-components/index.js
  src/stories/BlockRemoveSearchFilter.stories.js
  src/stories/BlockTag.spec.js
  src/stories/BlockTag.stories.js
  src/styles/_base.scss
  src/styles/_default-theme.scss
  src/styles/_ftva-theme.scss
  src/styles/default/_blockremovesearchfilter.scss
  src/styles/default/_blocktag.scss
  src/styles/ftva/_blockremovesearchfilter.scss
  src/styles/ftva/_blocktag.scss
  src/styles/themes.scss
Labels: feature

#525 fix: grey placeholder appreaing under email address label when not in focus
  src/lib-components/FooterPrimary.vue
Labels: bugfix

#526 fix: convert isdark and isSmallSize to boolean and test if string is true in flexible component
  src/lib-components/BlockCallToAction.vue
  src/lib-components/BlockCallToActionTwoUp.vue
  src/lib-components/Flexible/CallToAction.vue
  src/lib-components/Flexible/CtaBlock2Up.vue
  src/lib-components/FlexibleBlocks.vue
  src/lib-components/FooterPrimary.vue
  src/lib-components/index.js
  src/stories/BlockCallToAction.stories.js
  src/stories/BlockCallToActionTwoUp.stories.js
  src/stories/Flexible_CallToAction2Up.spec.js
  src/stories/Flexible_CallToAction2Up.stories.js
  src/types/flexible_types.ts
Labels: bugfix

#534 feat: APPS-2777 fix nitro crawling issue
  package.json
  pnpm-lock.yaml
  vite.config.ts
Labels: bugfix, feature, refactor

#528 feat: Apps-2773 update responsive image component
  package.json
  pnpm-lock.yaml
  src/lib-components/ResponsiveImage.vue
  src/stories/ResponsiveImage.spec.js
  src/stories/ResponsiveImage.stories.js
Labels: feature

#531 feat: Apps-2704 finish tags component part 2
  package.json
  pnpm-lock.yaml
  src/lib-components/BlockRemoveSearchFilter.vue
  src/lib-components/BlockTag.vue
  src/stories/BlockRemoveSearchFilter.stories.js
  src/stories/BlockTag.stories.js
  src/styles/_base.scss
  src/styles/ftva/_blockremovesearchfilter.scss
  src/styles/ftva/_blocktag.scss
Labels: feature

#529 feat: APPS-2707 Create FTVA BlockInfo component
  package.json
  src/lib-components/BlockInfo.vue
  src/lib-components/ButtonLink.vue
  src/lib-components/index.js
  src/stories/BlockInfo.spec.js
  src/stories/BlockInfo.stories.js
  src/stories/ButtonLink.stories.js
  src/styles/_base.scss
  src/styles/_ftva-theme.scss
  src/styles/default/_button-link.scss
  src/styles/ftva/_block-info.scss
  src/styles/ftva/_button-link.scss
Labels: feature

#527 feat: Apps-2706 create BlockEventDetail component
  src/lib-components/BlockEventDetail.vue
  src/stories/BlockEventDetail.spec.js
  src/stories/BlockEventDetail.stories.js
  src/styles/_base.scss
  src/styles/_ftva-theme.scss
  src/styles/default/_blockeventdetail.scss
  src/styles/ftva/_blockeventdetail.scss
Labels: feature
