Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2024-08, with the labels that each got.

#578 fix: APPS-2856 VideoEmbed Responsiveness
  src/lib-components/VideoEmbed.vue
Labels: fix

#579 fix: APPS-2858 Remove Trailing Dates from NavBeadcrumbs
  src/lib-components/NavBreadcrumb.vue
  src/stories/NavBreadcrumb.stories.js
Labels: fix

#581 fix: APPS-2825 Fix MastheadSecondary Height
  src/lib-components/MastheadSecondary.vue
Labels: fix

#577 fix: APPS-2827 Component SectionTeaserCard
  src/lib-components/BlockCardWithImage.vue
  src/lib-components/CardMeta.vue
  src/lib-components/SectionTeaserCard.vue
  src/stories/BlockCardWithImage.stories.js
  src/stories/SectionTeaserCard.stories.js
  src/styles/default/_section-teaser-card.scss
  src/styles/ftva/_block-card-with-image.scss
  src/styles/ftva/_section-teaser-card.scss
Labels: fix

#567 feat: APPS-2798 Create ButtonDropdown Component
  package.json
  pnpm-lock.yaml
  src/lib-components/ButtonDropdown.vue
  src/lib-components/IconWithLink.vue
  src/lib-components/index.js
  src/stories/ButtonDropdown.spec.js
  src/stories/ButtonDropdown.stories.js
  src/stories/IconWithLink.stories.js
  src/styles/_base.scss
  src/styles/_ftva-theme.scss
  src/styles/default/_button-dropdown.scss
  src/styles/ftva/_button-dropdown.scss
  src/utils/removeTags.js
  vite.config.ts
Labels: feature

#583 fix: APPS-2876 Component BlockEventDetail - No map icon If no location
  src/lib-components/BlockEventDetail.vue
  src/stories/BlockEventDetail.stories.js
Labels: fix

#582 fix: APPS-2870 Component CardMeta in RichText - Text is truncated when it shouldn't be
  src/lib-components/CardMeta.vue
  src/stories/CardMeta.stories.js
  src/styles/ftva/_card-meta.scss
Labels: bugfix

#586 fix: update vite.config.js external ['vue', 'vue-router', 'pinia']
  vite.config.ts
Labels: fix

#580 feat: APPS-2699 update footer for ftva theme
  src/lib-components/FooterLinks.vue
  src/lib-components/FooterMain.vue
  src/lib-components/FooterPrimary.vue
  src/lib-components/FooterSock.vue
  src/lib-components/index.js
  src/stores/GlobalStore.js
  src/stores/mock.js
  src/stories/FooterLinks.specs.js
  src/stories/FooterLinks.stories.js
  src/stories/FooterMain.stories.js
  src/stories/FooterPrimary.stories.js
  src/stories/FooterSock.stories.js
  src/styles/default/_footer-links.scss
  src/styles/default/_footer-primary.scss
  src/styles/default/_footer-sock.scss
  src/styles/ftva/_footer-links.scss
  src/styles/ftva/_footer-primary.scss
  src/styles/ftva/_footer-sock.scss
  src/styles/global.scss
Labels: feature

#587 feat: APPS-2888 Add debug prop to Dropdown Calendar
  src/lib-components/ButtonDropdown.vue
  src/styles/default/_button-dropdown.scss
Labels: enhancement

#588 chore: refactor theme pattern to rescope styles, add deep() where needed
  .storybook/main.ts
  src/lib-components/BlockCardWithImage.vue
  src/lib-components/BlockEventDetail.vue
  src/lib-components/BlockInfo.vue
  src/lib-components/BlockRemoveSearchFilter.vue
  src/lib-components/BlockScreeningDetail.vue
  src/lib-components/BlockTag.vue
  src/lib-components/ButtonDropdown.vue
  src/lib-components/ButtonLink.vue
  src/lib-components/CardMeta.vue
  src/lib-components/DateFilter.vue
  src/lib-components/DividerWayFinder.vue
  src/lib-components/Flexible/MediaGallery/NewLightbox.vue
  src/lib-components/FooterLinks.vue
  src/lib-components/FooterPrimary.vue
  src/lib-components/FooterSock.vue
  src/lib-components/NavBreadcrumb.vue
  src/lib-components/NavSearch.vue
  src/lib-components/SectionTeaserCard.vue
  src/styles/_ftva-theme.scss
  src/styles/default/_block-info.scss
  src/styles/default/_block-screening-detail.scss
  src/styles/ftva/_block-card-with-image.scss
  src/styles/global.scss
  vite.config.ts
Labels: chore

#585 fix: Apps-2852 fix blockhours height
  src/lib-components/BlockHours.vue
Labels: bugfix

#592 fix: APPS-2852 block hours
  README.md
  package.json
  pnpm-lock.yaml
  public/blockCliccHours.html
  public/blockHours.html
  src/lib-components/BlockHours.vue
  src/stories/BlockHours.stories.js
  src/stories/SectionWrapper.stories.js
  vite.config.ts
Labels: bugfix

#593 fix: Add production url back for blockhours
  src/lib-components/BlockHours.vue
Labels: bugfix

#594 fix: Revert "fix: Add production url back for blockhours"
  src/lib-components/BlockHours.vue
Labels: bugfix

#595 fix: Revert "fix: APPS-2852 block hours"
  README.md
  package.json
  pnpm-lock.yaml
  public/blockCliccHours.html
  public/blockHours.html
  src/lib-components/BlockHours.vue
  src/stories/BlockHours.stories.js
  src/stories/SectionWrapper.stories.js
  vite.config.ts
Labels: bugfix

#574 feat: APPS-2821 Add FTVA theme to RichText component
  src/lib-components/RichText.vue
  src/stories/RichText.stories.js
  src/styles/_base.scss
  src/styles/_ftva-theme.scss
  src/styles/default/_rich-text.scss
  src/styles/ftva/_rich-text.scss
Labels: feature

#596 chore: APPS-2894 Fix storybook configure page mdx error
  vite.config.ts
Labels: chore

#590 fix: APPS-2882 part 1: increase max-width of sectionTeaserCard & sectionWrapper for ftva theme
  src/lib-components/SectionWrapper.vue
  src/styles/default/_section-wrapper.scss
  src/styles/ftva/_block-card-with-image.scss
  src/styles/ftva/_footer-links.scss
  src/styles/ftva/_footer-primary.scss
  src/styles/ftva/_footer-sock.scss
  src/styles/ftva/_section-teaser-card.scss
  src/styles/ftva/_section-wrapper.scss
  src/styles/global.scss
Labels: bugfix, fix

#591 feat: APPS-2698 create ftva header
  package.json
  pnpm-lock.yaml
  src/lib-components/ButtonLink.vue
  src/lib-components/HeaderSticky.vue
  src/lib-components/NavMenuItem.vue
  src/lib-components/NavPrimary.vue
  src/lib-components/NavSearch.vue
  src/lib-components/SiteBrandBar.vue
  src/stories/HeaderSticky.stories.js
  src/stories/NavPrimary.stories.js
  src/stories/SiteBrandBar.stories.js
  src/styles/default/_header-sticky.scss
  src/styles/default/_nav-menu-item.scss
  src/styles/default/_nav-primary.scss
  src/styles/default/_nav-search.scss
  src/styles/default/_site-brand-bar.scss
  src/styles/ftva/_header-sticky.scss
  src/styles/ftva/_nav-menu-item.scss
  src/styles/ftva/_nav-primary.scss
  src/styles/ftva/_nav-search.scss
  src/styles/ftva/_site-brand-bar.scss
Labels: feature
