Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2024-09, with the labels that each got.

#599 feat: Add ftva theme to sectionwrapper and paleblue theme to scss file
  src/lib-components/SectionWrapper.vue
  src/stories/SectionWrapper.stories.js
  src/styles/ftva/_section-wrapper.scss
Labels: feature

#601 feat: APPS-2920 theme to toggle 'multiple locations'
  src/lib-components/BlockEventDetail.vue
  src/stories/BlockEventDetail.stories.js
Labels: feature

#604 feat: APPS-2919 add slot to sectionwrapper for link
  src/lib-components/SectionWrapper.vue
  src/stories/SectionWrapper.stories.js
  src/styles/default/_section-wrapper.scss
  src/styles/ftva/_section-teaser-card.scss
  src/styles/ftva/_section-wrapper.scss
Labels: feature

#603 feat: APPS-2822 Create TabToggle
  src/lib-components/TabItem.vue
  src/lib-components/TabList.vue
  src/lib-components/index.js
  src/stories/TabToggle.spec.js
  src/stories/TabToggle.stories.js
  src/styles/default/_tab-item.scss
  src/styles/default/_tab-list.scss
  src/styles/ftva/_tab-item.scss
  src/styles/ftva/_tab-list.scss
Labels: feature

#605 fix: APPS-2914 NavBreadcrumb hydration error
  src/lib-components/DividerWayFinder.vue
  src/lib-components/NavBreadcrumb.vue
  src/stories/NavBreadcrumb.stories.js
Labels: fix

#602 feat: APPS-2917 FTVA series date variation
  src/lib-components/CardMeta.vue
  src/stories/CardMeta.stories.js
  src/stories/SectionTeaserCard.stories.js
  src/stories/SectionWrapper.stories.js
  src/styles/ftva/_block-card-with-image.scss
  src/styles/ftva/_section-wrapper.scss
  src/utils/formatEventDates.js
Labels: feature

#606 fix: APPS-2926 VideoEmbed cover image sizing
  src/lib-components/VideoEmbed.vue
Labels: fix

#607 feat: APPS-2941 add enddate, ongoing props to blockeventdetail.vue
  src/lib-components/BlockEventDetail.vue
  src/stories/BlockEventDetail.stories.js
  src/utils/formatEventDates.js
Labels: feature

#608 feat: APPS 2940 Animate TabToggle component
  src/lib-components/TabList.vue
  src/styles/default/_tab-list.scss
Labels: enhancement

#610 fix: APP-2937 Remove gap between FTVA event cards
  src/stories/SectionWrapper.stories.js
  src/styles/ftva/_section-teaser-card.scss
  src/styles/ftva/_section-wrapper.scss
Labels: fix

#612 fix: overflowing long text in ftva menu
  src/stories/HeaderSticky.stories.js
  src/styles/ftva/_header-sticky.scss
Labels: fix

#600 feat: APPS-2823 Create Card Horizontal Variation for FTVA
  src/lib-components/BlockCardThreeColumn.vue
  src/lib-components/BlockClippedDate.vue
  src/lib-components/CardMeta.vue
  src/lib-components/SectionTeaserList.vue
  src/lib-components/index.js
  src/stories/BlockCardThreeColumn.spec.js
  src/stories/BlockCardThreeColumn.stories.js
  src/stories/SectionTeaserList.stories.js
  src/styles/ftva/_card-meta.scss
  src/types/types.ts
  src/utils/formatFullDay.js
Labels: feature

#611 feat: APPS-2943 Add initialTab setting option to TabToggle
  src/lib-components/TabItem.vue
  src/lib-components/TabList.vue
  src/stories/TabToggle.stories.js
  src/styles/default/_tab-list.scss
Labels: enhancement

#614 feat: APPS-2946 Create Two Column Layout component
  src/documentation/TwoColLayoutWSticky.drawio
  src/documentation/TwoColLayoutWSticky.svg
  src/lib-components/TwoColLayoutWStickySideBar.vue
  src/lib-components/index.js
  src/stories/TwoColLayoutStickySideBar.spec.js
  src/stories/TwoColLayoutWStickySideBar.stories.js
Labels: feature

#616 fix: APPS-2947 Update NavBreadcrumb logic to display route title or prop title
  src/lib-components/NavBreadcrumb.vue
  src/stories/NavBreadcrumb.stories.js
Labels: refactor

#617 feat: APPS-2957 Create FTVA Pullquote
  src/lib-components/PullQuote.vue
  src/stories/PullQuote.stories.js
  src/styles/default/_pull-quote.scss
  src/styles/ftva/_pull-quote.scss
Labels: feature

#620 fix: APPS-2982 Remove excess padding values
  src/lib-components/TwoColLayoutWStickySideBar.vue
Labels: fix

#619 chore: APPS-2962 move styles from page to story
  src/styles/ftva/_section-teaser-card.scss
Labels: chore

#618 feat: Apps-2951 card meta changes for article detail page
  src/lib-components/CardMeta.vue
  src/stories/CardMeta.stories.js
  src/styles/ftva/_card-meta.scss
Labels: feature

#623 feat: APPS-2916 fix hydration and undefined errors
  src/lib-components/HeaderMain.vue
  src/lib-components/HeaderSmart.vue
  src/lib-components/IconWithLink.vue
  src/lib-components/NavPrimary.vue
  src/lib-components/NavSecondary.vue
  src/stories/HeaderSmart.stories.js
  src/stories/NavPrimary.stories.js
  src/styles/ftva/_section-wrapper.scss
Labels: bugfix

#621 feat: APPS-2956 flexible-divider-way finder
  src/lib-components/DividerWayFinder.vue
  src/lib-components/Flexible/HorizontalDivider.vue
  src/lib-components/index.js
  src/stories/Flexible_HorizontalDivider.spec.js
  src/stories/Flexible_HorizontalDivider.stories.js
  src/types/flexible_types.ts
Labels: feature

#624 fix: move watchers to onmounted and remove immediate:true for some watchers we don't need to run it immediately
  package.json
  src/lib-components/HeaderMain.vue
  src/lib-components/HeaderSmart.vue
  src/lib-components/NavPrimary.vue
  src/lib-components/NavSecondary.vue
Labels: bugfix
