Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2025-01, with the labels that each got.

#672 fix: APPS-3042 Embedded video height in RichText
  src/styles/default/_rich-text.scss
Labels: fix

#673 fix: APPS-3043 Add z-index to dropdown button
  src/styles/default/_button-dropdown.scss
Labels: fix

#675 fix: Add attribute inheritance when component has multiple root nodes
  src/lib-components/TabList.vue
Labels: bugfix

#677 feat: APPS-3107 create ftva variation of block card with image and card meta component for the article listing page
  src/lib-components/BlockCardWithImage.vue
  src/lib-components/CardMeta.vue
  src/stories/BlockCardWithImage.stories.js
  src/stories/CardMeta.stories.js
  src/stories/mock-api.json
  src/styles/ftva/_block-card-with-image.scss
  src/styles/ftva/_card-meta.scss
Labels: feature

#678 fix: APPS-3107 rich text update
  src/lib-components/CardMeta.vue
  src/stories/CardMeta.stories.js
  src/styles/ftva/_card-meta.scss
Labels: fix

#680 feat: add conditional slots to blockcardwithimage template
  src/lib-components/BlockCardWithImage.vue
  src/lib-components/BlockStaffSubjectLibrarian.vue
  src/lib-components/CardMeta.vue
  src/stories/BlockCardWithImage.stories.js
  src/stories/CardMeta.stories.js
Labels: bugfix

#681 fix: APPS-3158 update block card with image
  src/stories/BlockCardWithImage.stories.js
  src/styles/ftva/_block-card-with-image.scss
  src/styles/ftva/_card-meta.scss
Labels: fix
