Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2025-04, with the labels that each got.

#719 feat: Add configuration prop for All filter from alphabet browse by and add watcher to SearchGeneric component
  .gitignore
  packages/vue-component-library/src/lib-components/AlphabeticalBrowseBy.vue
  packages/vue-component-library/src/lib-components/SearchGeneric.vue
  packages/vue-component-library/src/stories/AlphabeticalBrowseBy.stories.js
Labels: bugfix, feature

#721 feat: selcted letter needs to reset to empty string after the filter is removed from search-generic search filters
  packages/vue-component-library/src/lib-components/AlphabeticalBrowseBy.vue
Labels: bugfix

#722 feat: Add slots to SearchResults.vue to support new requirement to show date time for events, series and workshops after title
  packages/vue-component-library/src/lib-components/SearchResult.vue
  packages/vue-component-library/src/stories/SearchResult.stories.js
Labels: feature

#720 feat: APPS-3236 create component request for flexible card with image ftva variation
  packages/vue-component-library/src/lib-components/BlockCardWithImage.vue
  packages/vue-component-library/src/lib-components/Flexible/CardWithImage.vue
  packages/vue-component-library/src/stories/FlexibleBlocks.stories.js
  packages/vue-component-library/src/stories/Flexible_CardWithImage.stories.js
  packages/vue-component-library/src/stories/SectionTeaserCard.stories.js
  packages/vue-component-library/src/stories/mock/FTVAMedia.js
  packages/vue-component-library/src/styles/_base.scss
  packages/vue-component-library/src/styles/_ftva-theme.scss
  packages/vue-component-library/src/styles/default/_flexible-block-card-with-image.scss
  packages/vue-component-library/src/styles/ftva/_flexible-block-card-with-image.scss
  packages/vue-component-library/src/types/flexible_types.ts
Labels: feature

#724 feat: APPS-3291 Update SectionTeaserCard for Collection Listings Types
  packages/vue-component-library/package.json
  packages/vue-component-library/src/lib-components/SectionTeaserCard.vue
  packages/vue-component-library/src/stories/SectionTeaserCard.stories.js
  packages/vue-component-library/src/styles/default/_section-teaser-card.scss
  packages/vue-component-library/src/styles/ftva/_section-teaser-card.scss
  packages/vue-component-library/src/types/types.ts
  pnpm-lock.yaml
Labels: enhancement

#725 feat: APPS-3292 theme PostSmall component to match about our collections items
  packages/vue-component-library/src/lib-components/BlockPostSmall.vue
  packages/vue-component-library/src/lib-components/SectionPostSmall.vue
  packages/vue-component-library/src/stories/BlockPostSmall.stories.js
  packages/vue-component-library/src/stories/SectionPostSmall.stories.js
  packages/vue-component-library/src/styles/_base.scss
  packages/vue-component-library/src/styles/_ftva-theme.scss
  packages/vue-component-library/src/styles/default/_block-post-small.scss
  packages/vue-component-library/src/styles/default/_section-post-small.scss
  packages/vue-component-library/src/styles/ftva/_block-post-small.scss
  packages/vue-component-library/src/styles/ftva/_section-post-small.scss
Labels: feature

#727 feat: APPS-3309 Update AlphabeticalBrowseBy with FTVA variant
  packages/vue-component-library/src/lib-components/AlphabeticalBrowseBy.vue
  packages/vue-component-library/src/styles/default/_alphabetical-browse-by.scss
  packages/vue-component-library/src/styles/ftva/_alphabetical-browse-by.scss
Labels: enhancement

#730 feat: fix hydration issue with sectionpostsmall and have single source of truth and refactor to script setup AlphabeticalBrowseBy component
  packages/vue-component-library/src/lib-components/AlphabeticalBrowseBy.vue
  packages/vue-component-library/src/lib-components/SectionPostSmall.vue
  packages/vue-component-library/src/stories/AlphabeticalBrowseBy.stories.js
Labels: bugfix
