Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2025-05, with the labels that each got.

#731 fix: Replace watcher with onMounted and fix videoembed undefined error on ftva when trailer is not an iframe code from craft
  packages/vue-component-library/src/lib-components/AlphabeticalBrowseBy.vue
  packages/vue-component-library/src/lib-components/VideoEmbed.vue
  packages/vue-component-library/src/stories/AlphabeticalBrowseBy.stories.js
  packages/vue-component-library/src/styles/default/_alphabetical-browse-by.scss
  packages/vue-component-library/src/styles/ftva/_alphabetical-browse-by.scss
Labels: bugfix

#732 fix: APPS-3302 make cards within ScrollWrapper clickable
  packages/vue-component-library/src/index.ts
  packages/vue-component-library/src/lib-components/ScrollWrapper.vue
Labels: bugfix

#728 feat: APPS-1976 Add search Main library website navigation
  packages/vue-component-library/src/index.ts
  packages/vue-component-library/src/lib-components/HeaderMainResponsive.vue
  packages/vue-component-library/src/lib-components/NavSecondary.vue
  packages/vue-component-library/src/lib-components/SearchInput.vue
  packages/vue-component-library/src/lib-components/SearchMenuItem.vue
Labels: feature

#733 fix: APPS-3305 Fix missing FTVA FlexBlock CardWithImage default image
  packages/vue-component-library/src/lib-components/Flexible/CardWithImage.vue
  packages/vue-component-library/src/stories/mock/FTVAMedia.js
Labels: fix

#735 fix: nav search issue
  packages/vue-component-library/src/lib-components/SearchGeneric.vue
Labels: bugfix

#736 fix: watcher argument
  packages/vue-component-library/src/lib-components/SearchGeneric.vue
  packages/vue-component-library/src/lib-components/SearchInput.vue
Labels: bugfix

#738 fix: add a watcher to searchinput
  packages/vue-component-library/src/lib-components/HeaderMainResponsive.vue
  packages/vue-component-library/src/lib-components/SearchInput.vue
  packages/vue-component-library/src/lib-components/SearchMenuItem.vue
Labels: bugfix

#739 fix: reset querydropdownqueryFilterButtonDropDownStates when newQueryFilters is empty
  packages/vue-component-library/src/lib-components/SearchGenericFilters.vue
Labels: bugfix

#740 fix: Reset filters part1
  packages/vue-component-library/src/lib-components/BaseCheckboxGroup.vue
  packages/vue-component-library/src/lib-components/BaseRadioGroup.vue
  packages/vue-component-library/src/lib-components/SearchGenericFilters.vue
  packages/vue-component-library/src/lib-components/SectionRemoveSearchFilter.vue
Labels: bugfix

#741 fix: reset remove filter list and add onmounted in basecheckboxgroup
  packages/vue-component-library/src/lib-components/BaseCheckboxGroup.vue
  packages/vue-component-library/src/lib-components/SectionRemoveSearchFilter.vue
Labels: bugfix

#742 fix: Search words reset
  packages/vue-component-library/src/lib-components/BaseCheckboxGroup.vue
  packages/vue-component-library/src/lib-components/BaseRadioGroup.vue
  packages/vue-component-library/src/lib-components/SearchGeneric.vue
  packages/vue-component-library/src/lib-components/SearchGenericFilters.vue
  packages/vue-component-library/src/lib-components/SearchInput.vue
  packages/vue-component-library/src/lib-components/SearchMenuItem.vue
  packages/vue-component-library/src/lib-components/SectionRemoveSearchFilter.vue
Labels: bugfix

#743 fix: Search words reset part1
  packages/vue-component-library/src/lib-components/SearchMenuItem.vue
Labels: bugfix

#737 feat: APPS-3320 Create MediaWithText FTVA variants
  packages/vue-component-library/src/lib-components/BlockMediaWithText.vue
  packages/vue-component-library/src/lib-components/Flexible/MediaWithText.vue
  packages/vue-component-library/src/stories/BlockMediaWithText.stories.js
  packages/vue-component-library/src/stories/Flexible_MediaWithText.stories.js
  packages/vue-component-library/src/stories/mock/BlockMediaWithText.js
  packages/vue-component-library/src/stories/mock/FTVAMedia.js
  packages/vue-component-library/src/stories/mock/Flexible_MediaWithText.js
  packages/vue-component-library/src/styles/default/_block-media-with-text.scss
  packages/vue-component-library/src/styles/default/_flexible-media-with-text.scss
  packages/vue-component-library/src/styles/ftva/_block-media-with-text.scss
  packages/vue-component-library/src/styles/ftva/_flexible-media-with-text.scss
Labels: enhancement

#744 feat: update route path and searchwords with route.query.q
  packages/vue-component-library/src/index.ts
  packages/vue-component-library/src/lib-components/NavSearch.vue
  packages/vue-component-library/src/lib-components/SearchMenuItem.vue
Labels: feature

#745 fix: APPS-3356 Component Fixes for Storytelling Page
  packages/vue-component-library/src/lib-components/SectionPostSmall.vue
  packages/vue-component-library/src/stories/SectionPostSmall.stories.js
  packages/vue-component-library/src/stories/mock/BlockMediaWithText.js
  packages/vue-component-library/src/stories/mock/FTVAMedia.js
  packages/vue-component-library/src/stories/mock/Flexible_MediaWithText.js
  packages/vue-component-library/src/styles/default/_section-post-small.scss
  packages/vue-component-library/src/styles/ftva/_block-card-with-image.scss
  packages/vue-component-library/src/styles/ftva/_block-media-with-text.scss
  packages/vue-component-library/src/styles/ftva/_block-post-small.scss
  packages/vue-component-library/src/styles/ftva/_section-post-small.scss
Labels: fix
