Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2025-02, with the labels that each got.

#679 refactor: APPS-3132 create new table component, deprecate sectionstafflibrarian BREAKING CHANGE
  src/lib-components/BlockStaffSubjectLibrarian.vue
  src/lib-components/SectionStaffSubjectLibrarian.vue
  src/lib-components/TableComponent.vue
  src/lib-components/TableRow.vue
  src/lib-components/index.js
  src/stories/BlockStaffSubjectLibrarian.spec.js
  src/stories/SectionStaffSubjectLibrarian.spec.js
  src/stories/SectionStaffSubjectLibrarian.stories.js
  src/stories/SectionWrapper.stories.js
  src/stories/TableComponent.spec.js
  src/stories/TableComponent.stories.js
  src/stories/TableRow.spec.js
  src/stories/TableRow.stories.js
  src/styles/default/_table-component.scss
  src/styles/default/_table-row.scss
  src/styles/ftva/_section-staff-subject-librarian.scss
  src/styles/ftva/_table-component.scss
  src/styles/ftva/_table-row.scss
Labels: breaking, refactor

#683 feat: update release config
  release.config.cjs
Labels: feature

#687 feat: APPS-3167 Update Table Component with PaleBlue theme
  src/stories/TableComponent.stories.js
  src/styles/ftva/_table-component.scss
Labels: enhancement

#685 feat: APPS-3165 Update SectionTeaserCard & BlockCardWIthImage for Collection Item page
  package.json
  pnpm-lock.yaml
  src/lib-components/BlockCardWithImage.vue
  src/lib-components/ResponsiveImage.vue
  src/lib-components/SectionTeaserCard.vue
  src/stories/BlockCardWithImage.stories.js
  src/stories/ResponsiveImage.stories.js
  src/stories/SectionTeaserCard.stories.js
  src/styles/default/_section-teaser-card.scss
  src/styles/ftva/_section-teaser-card.scss
  src/types/types.ts
Labels: feature

#686 feat: APPS-3157 create DefinitionList component
  src/lib-components/DefinitionList.vue
  src/lib-components/index.js
  src/stories/DefinitionList.spec.js
  src/stories/DefinitionList.stories.js
Labels: feature

#690 feat: APPS 3153 Create Flexible SimpleCards FTVA variant
  src/lib-components/BlockSimpleCard.vue
  src/lib-components/Flexible/SimpleCards.vue
  src/lib-components/SimpleCards.vue
  src/stories/BlockSimpleCard.stories.js
  src/stories/Flexible_SimpleCards.stories.js
  src/stories/SimpleCards.stories.js
  src/styles/default/_block-simple-card.scss
  src/styles/default/_simple-cards.scss
  src/styles/ftva/_block-simple-card.scss
  src/styles/ftva/_simple-cards.scss
Labels: feature

#689 feat: APPS-3148 add ftva theme to flexible form
  src/lib-components/Flexible/Form.vue
  src/stories/BlockForm.stories.js
  src/stories/Flexible_Form.stories.js
  src/styles/default/_block-form.scss
  src/styles/ftva/_block-form.scss
Labels: feature

#688 feat: APPS-3154 Add FTVA variation to Flexible CallToAction
  src/lib-components/BlockCallToAction.vue
  src/lib-components/Flexible/CallToAction.vue
  src/stories/BlockCallToAction.stories.js
  src/stories/ButtonLink.stories.js
  src/stories/Flexible_CallToAction.spec.js
  src/stories/Flexible_CallToAction.stories.js
  src/styles/default/_block-call-to-action.scss
  src/styles/ftva/_block-call-to-action.scss
  src/styles/ftva/_button-link.scss
Labels: feature

#692 feat: APPS-3150 add ftva theme to Flexible ImpactNumberCards
  src/lib-components/Flexible/ImpactNumberCards.vue
  src/lib-components/ImpactNumberCard.vue
  src/stories/Flexible_ImpactNumberCards.stories.js
  src/stories/ImpactNumberCard.stories.js
  src/styles/default/_impact-number-card.scss
  src/styles/default/_impact-number-cards.scss
  src/styles/ftva/_impact-number-card.scss
  src/styles/ftva/_impact-number-cards.scss
Labels: feature
