Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2025-03, with the labels that each got.

#691 feat: APPS-3149 FTVA styles for PageAnchor
  src/lib-components/PageAnchor.vue
  src/stories/PageAnchor.stories.js
  src/styles/default/_page-anchor.scss
  src/styles/ftva/_page-anchor.scss
Labels: feature

#694 feat: APPS-3147 Create FlexibleBlockInfo
  package.json
  pnpm-lock.yaml
  src/lib-components/BlockInfo.vue
  src/lib-components/Flexible/Info.vue
  src/lib-components/IconWithLink.vue
  src/lib-components/index.js
  src/stories/BlockInfo.stories.js
  src/stories/Flexible_Info.spec.js
  src/stories/Flexible_Info.stories.js
  src/stories/TwoColLayoutStickySideBar.spec.js
  src/stories/TwoColLayoutWStickySideBar.stories.js
  src/styles/default/_block-info.scss
  src/styles/ftva/_block-info.scss
  src/styles/ftva/_flexible-info.scss
Labels: feature

#697 fix: release config error
  packages/vue-component-library/release.config.cjs
Labels: bugfix

#698 fix: the plugin structure
  packages/vue-component-library/release.config.cjs
Labels: bugfix

#699 feat: rename the package so it is published in a different location
  .github/workflows/ci.yml
  .github/workflows/percy.yml
  .github/workflows/publish-to-npm.yml
  .github/workflows/setup-workspace/action.yml
  package.json
  packages/vue-component-library/package.json
Labels: enhancement, feature

#700 fix: use ucla-library-monorepo for temp release
  .github/workflows/ci.yml
  .github/workflows/percy.yml
  .github/workflows/publish-to-npm.yml
  .github/workflows/setup-workspace/action.yml
  package.json
  packages/vue-component-library/package.json
Labels: fix

#701 fix: Publish to ucla library monorepo
  .github/workflows/publish-to-npm.yml
  packages/vue-component-library/README.md
Labels: fix

#702 fix: APPS-3231 Delete BlockInfo styles moved to page-level
  packages/vue-component-library/src/styles/ftva/_block-info.scss
Labels: fix

#703 feat: APPS-3152 FlexibleBlocks add Info
  packages/vue-component-library/src/lib-components/FlexibleBlocks.vue
Labels: feature

#704 chore: Update Readme at root and in the package
  README.md
  package.json
  packages/vue-component-library/README.md
Labels: chore

#705 feat: APPS-3134 add nuxt-module to support auto imports
  .github/workflows/ci.yml
  .github/workflows/publish-to-npm.yml
  README.md
  package.json
  packages/component-library-nuxt-module/.editorconfig
  packages/component-library-nuxt-module/.gitignore
  packages/component-library-nuxt-module/.vscode/settings.json
  packages/component-library-nuxt-module/FORCE_RELEASE.txt
  packages/component-library-nuxt-module/README.md
  packages/component-library-nuxt-module/eslint.config.mjs
  packages/component-library-nuxt-module/package.json
  packages/component-library-nuxt-module/playground/app.vue
  packages/component-library-nuxt-module/playground/nuxt.config.ts
  packages/component-library-nuxt-module/playground/package.json
  packages/component-library-nuxt-module/playground/server/tsconfig.json
  packages/component-library-nuxt-module/playground/tsconfig.json
  packages/component-library-nuxt-module/release.config.cjs
  packages/component-library-nuxt-module/src/module.ts
  packages/component-library-nuxt-module/src/runtime/plugin.ts
  packages/component-library-nuxt-module/src/runtime/server/tsconfig.json
  packages/component-library-nuxt-module/src/types/ucla-library-website-components.d.ts
  packages/component-library-nuxt-module/test/basic.test.ts
  packages/component-library-nuxt-module/test/fixtures/basic/app.vue
  packages/component-library-nuxt-module/test/fixtures/basic/nuxt.config.ts
  packages/component-library-nuxt-module/test/fixtures/basic/package.json
  packages/component-library-nuxt-module/tsconfig.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: feature

#706 fix: update github actions
  .github/workflows/publish-to-npm.yml
Labels: bugfix

#708 fix: APPS-3247 Add FlexibleMediaText's missing Divider import
  packages/vue-component-library/src/lib-components/Flexible/MediaWithText.vue
Labels: fix

#710 feat: enable svgo and disable removeviewbox plugin this is what we did in vue2
  packages/component-library-nuxt-module/playground/app.vue
  packages/component-library-nuxt-module/playground/composables/provideTheme.ts
  packages/vue-component-library/vite.config.ts
Labels: feature

#713 feat: add section-title and section-summary
  packages/vue-component-library/src/lib-components/FlexibleBlocks.vue
Labels: feature

#711 fix: APPS-3263 Fix FTVA PageAnchor alignment
  packages/vue-component-library/src/stories/PageAnchor.stories.js
  packages/vue-component-library/src/styles/ftva/_page-anchor.scss
Labels: fix

#707 feat: APPS-3235 create scroll wrapper component
  packages/vue-component-library/package.json
  packages/vue-component-library/src/index.ts
  packages/vue-component-library/src/lib-components/FlexibleBlocks.vue
  packages/vue-component-library/src/lib-components/Fragment.vue
  packages/vue-component-library/src/lib-components/ScrollWrapper.vue
  packages/vue-component-library/src/lib-components/index.ts
  packages/vue-component-library/src/plugins/vuetify.ts
  packages/vue-component-library/src/stories/FlexibleBlocks.stories.js
  packages/vue-component-library/src/stories/ScrollWrapper.spec.js
  packages/vue-component-library/src/stories/ScrollWrapper.stories.js
  packages/vue-component-library/src/stories/SectionTeaserCard.stories.js
  packages/vue-component-library/src/stories/mock/FTVAMedia.js
  pnpm-lock.yaml
Labels: feature

#716 feat: fix flexibleinfo export
  packages/component-library-nuxt-module/package.json
  packages/vue-component-library/src/index.ts
  pnpm-lock.yaml
Labels: feature

#717 feat: revert svgo changes
  packages/vue-component-library/vite.config.ts
Labels: bugfix
