Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2025-07, with the labels that each got.

#748 feat: APPS-2805 Update Lightbox Theme for FTVA Homepage
  packages/vue-component-library/src/lib-components/Flexible/MediaGallery/NewLightbox.vue
  packages/vue-component-library/src/stories/MediaGallery_NewLightbox.stories.js
  packages/vue-component-library/src/stories/mock/FTVAMedia.js
  packages/vue-component-library/src/styles/ftva/_new-lightbox.scss
Labels: enhancement

#753 fix: APPS-3379 Fix FTVA Homepage Carousel mobile layout
  packages/vue-component-library/src/styles/ftva/_new-lightbox.scss
Labels: fix

#751 feat: APPS-3376 create image slider component
  packages/vue-component-library/src/index.ts
  packages/vue-component-library/src/lib-components/ImageSlider.vue
  packages/vue-component-library/src/stories/ImageSlider.spec.js
  packages/vue-component-library/src/stories/ImageSlider.stories.js
Labels: feature

#754 feat: add alt text
  packages/vue-component-library/src/lib-components/ImageSlider.vue
  packages/vue-component-library/src/stories/ImageSlider.stories.js
Labels: feature

#755 fix: APPS-3358 Fix typeMedia parsing error in FlexMediaWithText
  packages/vue-component-library/src/lib-components/Flexible/MediaWithText.vue
  packages/vue-component-library/src/stories/BlockMediaWithText.stories.js
  packages/vue-component-library/src/stories/mock/BlockMediaWithText.js
  packages/vue-component-library/src/stories/mock/FTVAMedia.js
  packages/vue-component-library/src/stories/mock/Flexible_MediaWithText.js
Labels: fix

#756 fix: clear filters when clear btn is clicked
  packages/vue-component-library/src/lib-components/FiltersDropdown.vue
Labels: fix

#761 fix: APPS-3346 navbar reacts properly when screen size is small
  packages/vue-component-library/src/stories/HeaderSticky.stories.js
  packages/vue-component-library/src/styles/ftva/_nav-primary.scss
Labels: fix

#764 fix: APPS-3031 Update category color and font-size for staff-article-list
  packages/vue-component-library/src/stories/BlockStaffArticleList.stories.js
  packages/vue-component-library/src/styles/ftva/_block-staff-article-item.scss
Labels: fix
