Repository UCLALibrary/ucla-library-website-components, pull requests merged in 2025-08, with the labels that each got.

#763 feat: APPS-3378 add SingleItem mode to ScrollWrapper
  packages/vue-component-library/src/lib-components/ScrollWrapper.vue
  packages/vue-component-library/src/plugins/vuetify.ts
  packages/vue-component-library/src/stories/ImageSlider.stories.js
  packages/vue-component-library/src/stories/ScrollWrapper.stories.js
  packages/vue-component-library/src/stories/SectionWrapper.stories.js
Labels: feature

#769 fix: APPS-3324 dropdown matches width of share button
  packages/vue-component-library/src/styles/ftva/_mobile-drawer.scss
Labels: fix

#772 fix: APPS-3159 fix z-score so that buttons disappear behind nav-bar
  packages/vue-component-library/src/lib-components/ImageSlider.vue
  packages/vue-component-library/src/styles/ftva/_button-dropdown.scss
Labels: fix

#777 fix: APPS-3198 border-radius calendar events
  packages/vue-component-library/src/stories/mock/CalendarEvents.js
  packages/vue-component-library/src/styles/default/_base-calendar.scss
  packages/vue-component-library/src/styles/ftva/_base-calendar.scss
Labels: fix

#778 docs: Add github action for adding labels when PR is opened with a conventional commit title
  .github/workflows/label-by-title.yml
Labels: fix

#779 fix: for forked PR's
  .github/workflows/ci.yml
Labels: fix

#781 fix: cypress after merge
  .github/workflows/ci.yml
Labels: fix

#783 fix: remove test.yml
  .github/workflows/test.yml
Labels: fix

#786 fix: Add check
  .github/workflows/ci.yml
Labels: fix

#776 fix: APPS-3033 Remove Nav Menu Page Overflow
  packages/vue-component-library/src/lib-components/NavPrimary.vue
  packages/vue-component-library/src/stories/BlockCardThreeColumn.stories.js
  packages/vue-component-library/src/styles/ftva/_header-sticky.scss
  packages/vue-component-library/src/styles/ftva/_nav-primary.scss
Labels: fix

#775 feat: APPS-3220 refactor styles to use classic table styles
  .github/workflows/setup-workspace/action.yml
  packages/vue-component-library/src/lib-components/TableComponent.vue
  packages/vue-component-library/src/stories/TableComponent.stories.js
  packages/vue-component-library/src/styles/default/_table-component.scss
  packages/vue-component-library/src/styles/default/_table-row.scss
  packages/vue-component-library/src/styles/ftva/_table-component.scss
  packages/vue-component-library/src/styles/ftva/_table-row.scss
Labels: enhancement, feature

#768 feat: APPS-3390 Refactor SectionStaffArticleList and BlockStaffArticleList
  packages/vue-component-library/package.json
  packages/vue-component-library/src/lib-components/BlockStaffArticleList.vue
  packages/vue-component-library/src/lib-components/SectionStaffArticleList.vue
  packages/vue-component-library/src/stories/BlockStaffArticleList.stories.js
  packages/vue-component-library/src/stories/SectionStaffArticleList.stories.js
  packages/vue-component-library/src/stories/mock/FTVASearchResultsData.js
  packages/vue-component-library/src/styles/default/_block-staff-article-item.scss
  packages/vue-component-library/src/styles/ftva/_block-staff-article-item.scss
  pnpm-lock.yaml
Labels: bugfix, feature, refactor

#792 fix: APPS-3397 title on homepage carousel is clickable
  packages/vue-component-library/src/lib-components/Flexible/MediaGallery/NewLightbox.vue
  packages/vue-component-library/src/stories/MediaGallery_NewLightbox.stories.js
Labels: fix

#793 fix: APPS-3399 make sitebrand route to correct URL for ftva
  packages/vue-component-library/src/lib-components/SectionStaffArticleList.vue
  packages/vue-component-library/src/lib-components/SiteBrandBar.vue
Labels: fix

#798 fix: Percy for forked pr
  .github/workflows/ci.yml
  .github/workflows/percy.yml
Labels: fix

#799 fix: Add percy check for forked
  .github/workflows/percy-both.yml
  .github/workflows/percy.yml
Labels: fix

#800 fix: Add percy branch for forked pr
  .github/workflows/percy.yml
Labels: fix

#801 fix: Add percy check for forked
  .github/workflows/percy.yml
Labels: fix

#774 feat: Add ButtonPageView
  COMPONENTS.md
  packages/vue-component-library/package.json
  packages/vue-component-library/src/lib-components/ButtonPageView.vue
  packages/vue-component-library/src/lib-components/SmartLink.vue
  packages/vue-component-library/src/stories/ButtonPageView.spec.js
  packages/vue-component-library/src/stories/ButtonPageView.stories.js
  packages/vue-component-library/src/stories/button.css
  packages/vue-component-library/src/styles/dlc/_button-page-view.scss
  pnpm-lock.yaml
Labels: feature
